#coding=utf8

try:
    from . import xspcomm as xsp
except Exception as e:
    import xspcomm as xsp

if __package__ or "." in __name__:
    from .libUT_WayLookup import *
else:
    from libUT_WayLookup import *


class DUTWayLookup(object):

    # initialize
    def __init__(self, *args, **kwargs):
        self.dut = DutUnifiedBase(*args)
        self.xclock = xsp.XClock(self.dut.pxcStep, self.dut.pSelf)
        self.xport  = xsp.XPort()
        self.xclock.Add(self.xport)
        self.event = self.xclock.getEvent()
        self.internal_signals = {}
        self.xcfg = xsp.XSignalCFG(self.dut.GetXSignalCFGPath(), self.dut.GetXSignalCFGBasePtr())
        

        # set output files
        if kwargs.get("waveform_filename"):
            self.dut.SetWaveform(kwargs.get("waveform_filename"))
        if kwargs.get("coverage_filename"):
            self.dut.SetCoverage(kwargs.get("coverage_filename"))

        # All pins
        self.clock = xsp.XPin(xsp.XData(0, xsp.XData.In), self.event)
        self.reset = xsp.XPin(xsp.XData(0, xsp.XData.In), self.event)
        self.io_flush = xsp.XPin(xsp.XData(0, xsp.XData.In), self.event)
        self.io_read_ready = xsp.XPin(xsp.XData(0, xsp.XData.In), self.event)
        self.io_read_valid = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.io_read_bits_entry_vSetIdx_0 = xsp.XPin(xsp.XData(8, xsp.XData.Out), self.event)
        self.io_read_bits_entry_vSetIdx_1 = xsp.XPin(xsp.XData(8, xsp.XData.Out), self.event)
        self.io_read_bits_entry_waymask_0 = xsp.XPin(xsp.XData(4, xsp.XData.Out), self.event)
        self.io_read_bits_entry_waymask_1 = xsp.XPin(xsp.XData(4, xsp.XData.Out), self.event)
        self.io_read_bits_entry_ptag_0 = xsp.XPin(xsp.XData(36, xsp.XData.Out), self.event)
        self.io_read_bits_entry_ptag_1 = xsp.XPin(xsp.XData(36, xsp.XData.Out), self.event)
        self.io_read_bits_entry_itlb_exception_0 = xsp.XPin(xsp.XData(2, xsp.XData.Out), self.event)
        self.io_read_bits_entry_itlb_exception_1 = xsp.XPin(xsp.XData(2, xsp.XData.Out), self.event)
        self.io_read_bits_entry_itlb_pbmt_0 = xsp.XPin(xsp.XData(2, xsp.XData.Out), self.event)
        self.io_read_bits_entry_itlb_pbmt_1 = xsp.XPin(xsp.XData(2, xsp.XData.Out), self.event)
        self.io_read_bits_entry_meta_codes_0 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.io_read_bits_entry_meta_codes_1 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.io_read_bits_gpf_gpaddr = xsp.XPin(xsp.XData(56, xsp.XData.Out), self.event)
        self.io_read_bits_gpf_isForVSnonLeafPTE = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.io_write_ready = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.io_write_valid = xsp.XPin(xsp.XData(0, xsp.XData.In), self.event)
        self.io_write_bits_entry_vSetIdx_0 = xsp.XPin(xsp.XData(8, xsp.XData.In), self.event)
        self.io_write_bits_entry_vSetIdx_1 = xsp.XPin(xsp.XData(8, xsp.XData.In), self.event)
        self.io_write_bits_entry_waymask_0 = xsp.XPin(xsp.XData(4, xsp.XData.In), self.event)
        self.io_write_bits_entry_waymask_1 = xsp.XPin(xsp.XData(4, xsp.XData.In), self.event)
        self.io_write_bits_entry_ptag_0 = xsp.XPin(xsp.XData(36, xsp.XData.In), self.event)
        self.io_write_bits_entry_ptag_1 = xsp.XPin(xsp.XData(36, xsp.XData.In), self.event)
        self.io_write_bits_entry_itlb_exception_0 = xsp.XPin(xsp.XData(2, xsp.XData.In), self.event)
        self.io_write_bits_entry_itlb_exception_1 = xsp.XPin(xsp.XData(2, xsp.XData.In), self.event)
        self.io_write_bits_entry_itlb_pbmt_0 = xsp.XPin(xsp.XData(2, xsp.XData.In), self.event)
        self.io_write_bits_entry_itlb_pbmt_1 = xsp.XPin(xsp.XData(2, xsp.XData.In), self.event)
        self.io_write_bits_entry_meta_codes_0 = xsp.XPin(xsp.XData(0, xsp.XData.In), self.event)
        self.io_write_bits_entry_meta_codes_1 = xsp.XPin(xsp.XData(0, xsp.XData.In), self.event)
        self.io_write_bits_gpf_gpaddr = xsp.XPin(xsp.XData(56, xsp.XData.In), self.event)
        self.io_write_bits_gpf_isForVSnonLeafPTE = xsp.XPin(xsp.XData(0, xsp.XData.In), self.event)
        self.io_update_valid = xsp.XPin(xsp.XData(0, xsp.XData.In), self.event)
        self.io_update_bits_blkPaddr = xsp.XPin(xsp.XData(42, xsp.XData.In), self.event)
        self.io_update_bits_vSetIdx = xsp.XPin(xsp.XData(8, xsp.XData.In), self.event)
        self.io_update_bits_waymask = xsp.XPin(xsp.XData(4, xsp.XData.In), self.event)
        self.io_update_bits_corrupt = xsp.XPin(xsp.XData(0, xsp.XData.In), self.event)
        self.WayLookup_readPtr_flag = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.WayLookup_readPtr_value = xsp.XPin(xsp.XData(5, xsp.XData.Out), self.event)
        self.WayLookup_writePtr_flag = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.WayLookup_writePtr_value = xsp.XPin(xsp.XData(5, xsp.XData.Out), self.event)
        self.WayLookup_gpf_hit = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.WayLookup_gpf_entry_valid = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.WayLookup_gpf_entry_bits_gpaddr = xsp.XPin(xsp.XData(56, xsp.XData.Out), self.event)
        self.WayLookup_entries_0_vSetIdx_0 = xsp.XPin(xsp.XData(8, xsp.XData.Out), self.event)
        self.WayLookup_entries_0_vSetIdx_1 = xsp.XPin(xsp.XData(8, xsp.XData.Out), self.event)
        self.WayLookup_entries_0_ptag_0 = xsp.XPin(xsp.XData(36, xsp.XData.Out), self.event)
        self.WayLookup_entries_0_ptag_1 = xsp.XPin(xsp.XData(36, xsp.XData.Out), self.event)
        self.WayLookup_entries_0_itlb_exception_0 = xsp.XPin(xsp.XData(2, xsp.XData.Out), self.event)
        self.WayLookup_entries_0_itlb_exception_1 = xsp.XPin(xsp.XData(2, xsp.XData.Out), self.event)
        self.WayLookup_entries_0_itlb_pbmt_0 = xsp.XPin(xsp.XData(2, xsp.XData.Out), self.event)
        self.WayLookup_entries_0_itlb_pbmt_1 = xsp.XPin(xsp.XData(2, xsp.XData.Out), self.event)
        self.WayLookup_entries_0_meta_codes_0 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.WayLookup_entries_0_meta_codes_1 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.WayLookup_vset_same = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.WayLookup_vset_same_1 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.WayLookup_vset_same_2 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.WayLookup_vset_same_3 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.WayLookup_vset_same_4 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.WayLookup_vset_same_5 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.WayLookup_vset_same_6 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.WayLookup_vset_same_7 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.WayLookup_vset_same_8 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.WayLookup_vset_same_9 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.WayLookup_vset_same_10 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.WayLookup_vset_same_11 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.WayLookup_vset_same_12 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.WayLookup_vset_same_13 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.WayLookup_vset_same_14 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.WayLookup_vset_same_15 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.WayLookup_vset_same_16 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.WayLookup_vset_same_17 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.WayLookup_vset_same_18 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.WayLookup_vset_same_19 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.WayLookup_vset_same_20 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.WayLookup_vset_same_21 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.WayLookup_vset_same_22 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.WayLookup_vset_same_23 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.WayLookup_vset_same_24 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.WayLookup_vset_same_25 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.WayLookup_vset_same_26 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.WayLookup_vset_same_27 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.WayLookup_vset_same_28 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.WayLookup_vset_same_29 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.WayLookup_vset_same_30 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.WayLookup_vset_same_31 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.WayLookup_vset_same_32 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.WayLookup_vset_same_33 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.WayLookup_vset_same_34 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.WayLookup_vset_same_35 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.WayLookup_vset_same_36 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.WayLookup_vset_same_37 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.WayLookup_vset_same_38 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.WayLookup_vset_same_39 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.WayLookup_vset_same_40 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.WayLookup_vset_same_41 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.WayLookup_vset_same_42 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.WayLookup_vset_same_43 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.WayLookup_vset_same_44 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.WayLookup_vset_same_45 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.WayLookup_vset_same_46 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.WayLookup_vset_same_47 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.WayLookup_vset_same_48 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.WayLookup_vset_same_49 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.WayLookup_vset_same_50 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.WayLookup_vset_same_51 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.WayLookup_vset_same_52 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.WayLookup_vset_same_53 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.WayLookup_vset_same_54 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.WayLookup_vset_same_55 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.WayLookup_vset_same_56 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.WayLookup_vset_same_57 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.WayLookup_vset_same_58 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.WayLookup_vset_same_59 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.WayLookup_vset_same_60 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.WayLookup_vset_same_61 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.WayLookup_vset_same_62 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.WayLookup_vset_same_63 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.WayLookup_ptag_same = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.WayLookup_ptag_same_1 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.WayLookup_ptag_same_2 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.WayLookup_ptag_same_3 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.WayLookup_ptag_same_4 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.WayLookup_ptag_same_5 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.WayLookup_ptag_same_6 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.WayLookup_ptag_same_7 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.WayLookup_ptag_same_8 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.WayLookup_ptag_same_9 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.WayLookup_ptag_same_10 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.WayLookup_ptag_same_11 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.WayLookup_ptag_same_12 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.WayLookup_ptag_same_13 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.WayLookup_ptag_same_14 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.WayLookup_ptag_same_15 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.WayLookup_ptag_same_16 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.WayLookup_ptag_same_17 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.WayLookup_ptag_same_18 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.WayLookup_ptag_same_19 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.WayLookup_ptag_same_20 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.WayLookup_ptag_same_21 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.WayLookup_ptag_same_22 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.WayLookup_ptag_same_23 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.WayLookup_ptag_same_24 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.WayLookup_ptag_same_25 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.WayLookup_ptag_same_26 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.WayLookup_ptag_same_27 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.WayLookup_ptag_same_28 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.WayLookup_ptag_same_29 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.WayLookup_ptag_same_30 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.WayLookup_ptag_same_31 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.WayLookup_ptag_same_32 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.WayLookup_ptag_same_33 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.WayLookup_ptag_same_34 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.WayLookup_ptag_same_35 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.WayLookup_ptag_same_36 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.WayLookup_ptag_same_37 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.WayLookup_ptag_same_38 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.WayLookup_ptag_same_39 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.WayLookup_ptag_same_40 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.WayLookup_ptag_same_41 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.WayLookup_ptag_same_42 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.WayLookup_ptag_same_43 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.WayLookup_ptag_same_44 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.WayLookup_ptag_same_45 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.WayLookup_ptag_same_46 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.WayLookup_ptag_same_47 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.WayLookup_ptag_same_48 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.WayLookup_ptag_same_49 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.WayLookup_ptag_same_50 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.WayLookup_ptag_same_51 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.WayLookup_ptag_same_52 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.WayLookup_ptag_same_53 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.WayLookup_ptag_same_54 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.WayLookup_ptag_same_55 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.WayLookup_ptag_same_56 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.WayLookup_ptag_same_57 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.WayLookup_ptag_same_58 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.WayLookup_ptag_same_59 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.WayLookup_ptag_same_60 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.WayLookup_ptag_same_61 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.WayLookup_ptag_same_62 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.WayLookup_ptag_same_63 = xsp.XPin(xsp.XData(0, xsp.XData.Out), self.event)
        self.WayLookup_entries_0_waymask_0 = xsp.XPin(xsp.XData(4, xsp.XData.Out), self.event)
        self.WayLookup_entries_0_waymask_1 = xsp.XPin(xsp.XData(4, xsp.XData.Out), self.event)
        self.WayLookup_entries_1_waymask_0 = xsp.XPin(xsp.XData(4, xsp.XData.Out), self.event)
        self.WayLookup_entries_1_waymask_1 = xsp.XPin(xsp.XData(4, xsp.XData.Out), self.event)
        self.WayLookup_entries_2_waymask_0 = xsp.XPin(xsp.XData(4, xsp.XData.Out), self.event)
        self.WayLookup_entries_2_waymask_1 = xsp.XPin(xsp.XData(4, xsp.XData.Out), self.event)
        self.WayLookup_entries_3_waymask_0 = xsp.XPin(xsp.XData(4, xsp.XData.Out), self.event)
        self.WayLookup_entries_3_waymask_1 = xsp.XPin(xsp.XData(4, xsp.XData.Out), self.event)
        self.WayLookup_entries_4_waymask_0 = xsp.XPin(xsp.XData(4, xsp.XData.Out), self.event)
        self.WayLookup_entries_4_waymask_1 = xsp.XPin(xsp.XData(4, xsp.XData.Out), self.event)
        self.WayLookup_entries_5_waymask_0 = xsp.XPin(xsp.XData(4, xsp.XData.Out), self.event)
        self.WayLookup_entries_5_waymask_1 = xsp.XPin(xsp.XData(4, xsp.XData.Out), self.event)
        self.WayLookup_entries_6_waymask_0 = xsp.XPin(xsp.XData(4, xsp.XData.Out), self.event)
        self.WayLookup_entries_6_waymask_1 = xsp.XPin(xsp.XData(4, xsp.XData.Out), self.event)
        self.WayLookup_entries_7_waymask_0 = xsp.XPin(xsp.XData(4, xsp.XData.Out), self.event)
        self.WayLookup_entries_7_waymask_1 = xsp.XPin(xsp.XData(4, xsp.XData.Out), self.event)
        self.WayLookup_entries_8_waymask_0 = xsp.XPin(xsp.XData(4, xsp.XData.Out), self.event)
        self.WayLookup_entries_8_waymask_1 = xsp.XPin(xsp.XData(4, xsp.XData.Out), self.event)
        self.WayLookup_entries_9_waymask_0 = xsp.XPin(xsp.XData(4, xsp.XData.Out), self.event)
        self.WayLookup_entries_9_waymask_1 = xsp.XPin(xsp.XData(4, xsp.XData.Out), self.event)
        self.WayLookup_entries_10_waymask_0 = xsp.XPin(xsp.XData(4, xsp.XData.Out), self.event)
        self.WayLookup_entries_10_waymask_1 = xsp.XPin(xsp.XData(4, xsp.XData.Out), self.event)
        self.WayLookup_entries_11_waymask_0 = xsp.XPin(xsp.XData(4, xsp.XData.Out), self.event)
        self.WayLookup_entries_11_waymask_1 = xsp.XPin(xsp.XData(4, xsp.XData.Out), self.event)
        self.WayLookup_entries_12_waymask_0 = xsp.XPin(xsp.XData(4, xsp.XData.Out), self.event)
        self.WayLookup_entries_12_waymask_1 = xsp.XPin(xsp.XData(4, xsp.XData.Out), self.event)
        self.WayLookup_entries_13_waymask_0 = xsp.XPin(xsp.XData(4, xsp.XData.Out), self.event)
        self.WayLookup_entries_13_waymask_1 = xsp.XPin(xsp.XData(4, xsp.XData.Out), self.event)
        self.WayLookup_entries_14_waymask_0 = xsp.XPin(xsp.XData(4, xsp.XData.Out), self.event)
        self.WayLookup_entries_14_waymask_1 = xsp.XPin(xsp.XData(4, xsp.XData.Out), self.event)
        self.WayLookup_entries_15_waymask_0 = xsp.XPin(xsp.XData(4, xsp.XData.Out), self.event)
        self.WayLookup_entries_15_waymask_1 = xsp.XPin(xsp.XData(4, xsp.XData.Out), self.event)
        self.WayLookup_entries_16_waymask_0 = xsp.XPin(xsp.XData(4, xsp.XData.Out), self.event)
        self.WayLookup_entries_16_waymask_1 = xsp.XPin(xsp.XData(4, xsp.XData.Out), self.event)
        self.WayLookup_entries_17_waymask_0 = xsp.XPin(xsp.XData(4, xsp.XData.Out), self.event)
        self.WayLookup_entries_17_waymask_1 = xsp.XPin(xsp.XData(4, xsp.XData.Out), self.event)
        self.WayLookup_entries_18_waymask_0 = xsp.XPin(xsp.XData(4, xsp.XData.Out), self.event)
        self.WayLookup_entries_18_waymask_1 = xsp.XPin(xsp.XData(4, xsp.XData.Out), self.event)
        self.WayLookup_entries_19_waymask_0 = xsp.XPin(xsp.XData(4, xsp.XData.Out), self.event)
        self.WayLookup_entries_19_waymask_1 = xsp.XPin(xsp.XData(4, xsp.XData.Out), self.event)
        self.WayLookup_entries_20_waymask_0 = xsp.XPin(xsp.XData(4, xsp.XData.Out), self.event)
        self.WayLookup_entries_20_waymask_1 = xsp.XPin(xsp.XData(4, xsp.XData.Out), self.event)
        self.WayLookup_entries_21_waymask_0 = xsp.XPin(xsp.XData(4, xsp.XData.Out), self.event)
        self.WayLookup_entries_21_waymask_1 = xsp.XPin(xsp.XData(4, xsp.XData.Out), self.event)
        self.WayLookup_entries_22_waymask_0 = xsp.XPin(xsp.XData(4, xsp.XData.Out), self.event)
        self.WayLookup_entries_22_waymask_1 = xsp.XPin(xsp.XData(4, xsp.XData.Out), self.event)
        self.WayLookup_entries_23_waymask_0 = xsp.XPin(xsp.XData(4, xsp.XData.Out), self.event)
        self.WayLookup_entries_23_waymask_1 = xsp.XPin(xsp.XData(4, xsp.XData.Out), self.event)
        self.WayLookup_entries_24_waymask_0 = xsp.XPin(xsp.XData(4, xsp.XData.Out), self.event)
        self.WayLookup_entries_24_waymask_1 = xsp.XPin(xsp.XData(4, xsp.XData.Out), self.event)
        self.WayLookup_entries_25_waymask_0 = xsp.XPin(xsp.XData(4, xsp.XData.Out), self.event)
        self.WayLookup_entries_25_waymask_1 = xsp.XPin(xsp.XData(4, xsp.XData.Out), self.event)
        self.WayLookup_entries_26_waymask_0 = xsp.XPin(xsp.XData(4, xsp.XData.Out), self.event)
        self.WayLookup_entries_26_waymask_1 = xsp.XPin(xsp.XData(4, xsp.XData.Out), self.event)
        self.WayLookup_entries_27_waymask_0 = xsp.XPin(xsp.XData(4, xsp.XData.Out), self.event)
        self.WayLookup_entries_27_waymask_1 = xsp.XPin(xsp.XData(4, xsp.XData.Out), self.event)
        self.WayLookup_entries_28_waymask_0 = xsp.XPin(xsp.XData(4, xsp.XData.Out), self.event)
        self.WayLookup_entries_28_waymask_1 = xsp.XPin(xsp.XData(4, xsp.XData.Out), self.event)
        self.WayLookup_entries_29_waymask_0 = xsp.XPin(xsp.XData(4, xsp.XData.Out), self.event)
        self.WayLookup_entries_29_waymask_1 = xsp.XPin(xsp.XData(4, xsp.XData.Out), self.event)
        self.WayLookup_entries_30_waymask_0 = xsp.XPin(xsp.XData(4, xsp.XData.Out), self.event)
        self.WayLookup_entries_30_waymask_1 = xsp.XPin(xsp.XData(4, xsp.XData.Out), self.event)
        self.WayLookup_entries_31_waymask_0 = xsp.XPin(xsp.XData(4, xsp.XData.Out), self.event)
        self.WayLookup_entries_31_waymask_1 = xsp.XPin(xsp.XData(4, xsp.XData.Out), self.event)


        # BindDPI or Native pin address
        self.clock.BindDPIPtr(self.dut.GetDPIHandle("clock", 0), self.dut.GetDPIHandle("clock", 1))
        self.reset.BindDPIPtr(self.dut.GetDPIHandle("reset", 0), self.dut.GetDPIHandle("reset", 1))
        self.io_flush.BindDPIPtr(self.dut.GetDPIHandle("io_flush", 0), self.dut.GetDPIHandle("io_flush", 1))
        self.io_read_ready.BindDPIPtr(self.dut.GetDPIHandle("io_read_ready", 0), self.dut.GetDPIHandle("io_read_ready", 1))
        self.io_read_valid.BindDPIPtr(self.dut.GetDPIHandle("io_read_valid", 0), self.dut.GetDPIHandle("io_read_valid", 1))
        self.io_read_bits_entry_vSetIdx_0.BindDPIPtr(self.dut.GetDPIHandle("io_read_bits_entry_vSetIdx_0", 0), self.dut.GetDPIHandle("io_read_bits_entry_vSetIdx_0", 1))
        self.io_read_bits_entry_vSetIdx_1.BindDPIPtr(self.dut.GetDPIHandle("io_read_bits_entry_vSetIdx_1", 0), self.dut.GetDPIHandle("io_read_bits_entry_vSetIdx_1", 1))
        self.io_read_bits_entry_waymask_0.BindDPIPtr(self.dut.GetDPIHandle("io_read_bits_entry_waymask_0", 0), self.dut.GetDPIHandle("io_read_bits_entry_waymask_0", 1))
        self.io_read_bits_entry_waymask_1.BindDPIPtr(self.dut.GetDPIHandle("io_read_bits_entry_waymask_1", 0), self.dut.GetDPIHandle("io_read_bits_entry_waymask_1", 1))
        self.io_read_bits_entry_ptag_0.BindDPIPtr(self.dut.GetDPIHandle("io_read_bits_entry_ptag_0", 0), self.dut.GetDPIHandle("io_read_bits_entry_ptag_0", 1))
        self.io_read_bits_entry_ptag_1.BindDPIPtr(self.dut.GetDPIHandle("io_read_bits_entry_ptag_1", 0), self.dut.GetDPIHandle("io_read_bits_entry_ptag_1", 1))
        self.io_read_bits_entry_itlb_exception_0.BindDPIPtr(self.dut.GetDPIHandle("io_read_bits_entry_itlb_exception_0", 0), self.dut.GetDPIHandle("io_read_bits_entry_itlb_exception_0", 1))
        self.io_read_bits_entry_itlb_exception_1.BindDPIPtr(self.dut.GetDPIHandle("io_read_bits_entry_itlb_exception_1", 0), self.dut.GetDPIHandle("io_read_bits_entry_itlb_exception_1", 1))
        self.io_read_bits_entry_itlb_pbmt_0.BindDPIPtr(self.dut.GetDPIHandle("io_read_bits_entry_itlb_pbmt_0", 0), self.dut.GetDPIHandle("io_read_bits_entry_itlb_pbmt_0", 1))
        self.io_read_bits_entry_itlb_pbmt_1.BindDPIPtr(self.dut.GetDPIHandle("io_read_bits_entry_itlb_pbmt_1", 0), self.dut.GetDPIHandle("io_read_bits_entry_itlb_pbmt_1", 1))
        self.io_read_bits_entry_meta_codes_0.BindDPIPtr(self.dut.GetDPIHandle("io_read_bits_entry_meta_codes_0", 0), self.dut.GetDPIHandle("io_read_bits_entry_meta_codes_0", 1))
        self.io_read_bits_entry_meta_codes_1.BindDPIPtr(self.dut.GetDPIHandle("io_read_bits_entry_meta_codes_1", 0), self.dut.GetDPIHandle("io_read_bits_entry_meta_codes_1", 1))
        self.io_read_bits_gpf_gpaddr.BindDPIPtr(self.dut.GetDPIHandle("io_read_bits_gpf_gpaddr", 0), self.dut.GetDPIHandle("io_read_bits_gpf_gpaddr", 1))
        self.io_read_bits_gpf_isForVSnonLeafPTE.BindDPIPtr(self.dut.GetDPIHandle("io_read_bits_gpf_isForVSnonLeafPTE", 0), self.dut.GetDPIHandle("io_read_bits_gpf_isForVSnonLeafPTE", 1))
        self.io_write_ready.BindDPIPtr(self.dut.GetDPIHandle("io_write_ready", 0), self.dut.GetDPIHandle("io_write_ready", 1))
        self.io_write_valid.BindDPIPtr(self.dut.GetDPIHandle("io_write_valid", 0), self.dut.GetDPIHandle("io_write_valid", 1))
        self.io_write_bits_entry_vSetIdx_0.BindDPIPtr(self.dut.GetDPIHandle("io_write_bits_entry_vSetIdx_0", 0), self.dut.GetDPIHandle("io_write_bits_entry_vSetIdx_0", 1))
        self.io_write_bits_entry_vSetIdx_1.BindDPIPtr(self.dut.GetDPIHandle("io_write_bits_entry_vSetIdx_1", 0), self.dut.GetDPIHandle("io_write_bits_entry_vSetIdx_1", 1))
        self.io_write_bits_entry_waymask_0.BindDPIPtr(self.dut.GetDPIHandle("io_write_bits_entry_waymask_0", 0), self.dut.GetDPIHandle("io_write_bits_entry_waymask_0", 1))
        self.io_write_bits_entry_waymask_1.BindDPIPtr(self.dut.GetDPIHandle("io_write_bits_entry_waymask_1", 0), self.dut.GetDPIHandle("io_write_bits_entry_waymask_1", 1))
        self.io_write_bits_entry_ptag_0.BindDPIPtr(self.dut.GetDPIHandle("io_write_bits_entry_ptag_0", 0), self.dut.GetDPIHandle("io_write_bits_entry_ptag_0", 1))
        self.io_write_bits_entry_ptag_1.BindDPIPtr(self.dut.GetDPIHandle("io_write_bits_entry_ptag_1", 0), self.dut.GetDPIHandle("io_write_bits_entry_ptag_1", 1))
        self.io_write_bits_entry_itlb_exception_0.BindDPIPtr(self.dut.GetDPIHandle("io_write_bits_entry_itlb_exception_0", 0), self.dut.GetDPIHandle("io_write_bits_entry_itlb_exception_0", 1))
        self.io_write_bits_entry_itlb_exception_1.BindDPIPtr(self.dut.GetDPIHandle("io_write_bits_entry_itlb_exception_1", 0), self.dut.GetDPIHandle("io_write_bits_entry_itlb_exception_1", 1))
        self.io_write_bits_entry_itlb_pbmt_0.BindDPIPtr(self.dut.GetDPIHandle("io_write_bits_entry_itlb_pbmt_0", 0), self.dut.GetDPIHandle("io_write_bits_entry_itlb_pbmt_0", 1))
        self.io_write_bits_entry_itlb_pbmt_1.BindDPIPtr(self.dut.GetDPIHandle("io_write_bits_entry_itlb_pbmt_1", 0), self.dut.GetDPIHandle("io_write_bits_entry_itlb_pbmt_1", 1))
        self.io_write_bits_entry_meta_codes_0.BindDPIPtr(self.dut.GetDPIHandle("io_write_bits_entry_meta_codes_0", 0), self.dut.GetDPIHandle("io_write_bits_entry_meta_codes_0", 1))
        self.io_write_bits_entry_meta_codes_1.BindDPIPtr(self.dut.GetDPIHandle("io_write_bits_entry_meta_codes_1", 0), self.dut.GetDPIHandle("io_write_bits_entry_meta_codes_1", 1))
        self.io_write_bits_gpf_gpaddr.BindDPIPtr(self.dut.GetDPIHandle("io_write_bits_gpf_gpaddr", 0), self.dut.GetDPIHandle("io_write_bits_gpf_gpaddr", 1))
        self.io_write_bits_gpf_isForVSnonLeafPTE.BindDPIPtr(self.dut.GetDPIHandle("io_write_bits_gpf_isForVSnonLeafPTE", 0), self.dut.GetDPIHandle("io_write_bits_gpf_isForVSnonLeafPTE", 1))
        self.io_update_valid.BindDPIPtr(self.dut.GetDPIHandle("io_update_valid", 0), self.dut.GetDPIHandle("io_update_valid", 1))
        self.io_update_bits_blkPaddr.BindDPIPtr(self.dut.GetDPIHandle("io_update_bits_blkPaddr", 0), self.dut.GetDPIHandle("io_update_bits_blkPaddr", 1))
        self.io_update_bits_vSetIdx.BindDPIPtr(self.dut.GetDPIHandle("io_update_bits_vSetIdx", 0), self.dut.GetDPIHandle("io_update_bits_vSetIdx", 1))
        self.io_update_bits_waymask.BindDPIPtr(self.dut.GetDPIHandle("io_update_bits_waymask", 0), self.dut.GetDPIHandle("io_update_bits_waymask", 1))
        self.io_update_bits_corrupt.BindDPIPtr(self.dut.GetDPIHandle("io_update_bits_corrupt", 0), self.dut.GetDPIHandle("io_update_bits_corrupt", 1))
        self.WayLookup_readPtr_flag.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_readPtr_flag", 0), self.dut.GetDPIHandle("WayLookup_readPtr_flag", 1))
        self.WayLookup_readPtr_value.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_readPtr_value", 0), self.dut.GetDPIHandle("WayLookup_readPtr_value", 1))
        self.WayLookup_writePtr_flag.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_writePtr_flag", 0), self.dut.GetDPIHandle("WayLookup_writePtr_flag", 1))
        self.WayLookup_writePtr_value.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_writePtr_value", 0), self.dut.GetDPIHandle("WayLookup_writePtr_value", 1))
        self.WayLookup_gpf_hit.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_gpf_hit", 0), self.dut.GetDPIHandle("WayLookup_gpf_hit", 1))
        self.WayLookup_gpf_entry_valid.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_gpf_entry_valid", 0), self.dut.GetDPIHandle("WayLookup_gpf_entry_valid", 1))
        self.WayLookup_gpf_entry_bits_gpaddr.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_gpf_entry_bits_gpaddr", 0), self.dut.GetDPIHandle("WayLookup_gpf_entry_bits_gpaddr", 1))
        self.WayLookup_entries_0_vSetIdx_0.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_entries_0_vSetIdx_0", 0), self.dut.GetDPIHandle("WayLookup_entries_0_vSetIdx_0", 1))
        self.WayLookup_entries_0_vSetIdx_1.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_entries_0_vSetIdx_1", 0), self.dut.GetDPIHandle("WayLookup_entries_0_vSetIdx_1", 1))
        self.WayLookup_entries_0_ptag_0.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_entries_0_ptag_0", 0), self.dut.GetDPIHandle("WayLookup_entries_0_ptag_0", 1))
        self.WayLookup_entries_0_ptag_1.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_entries_0_ptag_1", 0), self.dut.GetDPIHandle("WayLookup_entries_0_ptag_1", 1))
        self.WayLookup_entries_0_itlb_exception_0.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_entries_0_itlb_exception_0", 0), self.dut.GetDPIHandle("WayLookup_entries_0_itlb_exception_0", 1))
        self.WayLookup_entries_0_itlb_exception_1.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_entries_0_itlb_exception_1", 0), self.dut.GetDPIHandle("WayLookup_entries_0_itlb_exception_1", 1))
        self.WayLookup_entries_0_itlb_pbmt_0.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_entries_0_itlb_pbmt_0", 0), self.dut.GetDPIHandle("WayLookup_entries_0_itlb_pbmt_0", 1))
        self.WayLookup_entries_0_itlb_pbmt_1.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_entries_0_itlb_pbmt_1", 0), self.dut.GetDPIHandle("WayLookup_entries_0_itlb_pbmt_1", 1))
        self.WayLookup_entries_0_meta_codes_0.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_entries_0_meta_codes_0", 0), self.dut.GetDPIHandle("WayLookup_entries_0_meta_codes_0", 1))
        self.WayLookup_entries_0_meta_codes_1.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_entries_0_meta_codes_1", 0), self.dut.GetDPIHandle("WayLookup_entries_0_meta_codes_1", 1))
        self.WayLookup_vset_same.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_vset_same", 0), self.dut.GetDPIHandle("WayLookup_vset_same", 1))
        self.WayLookup_vset_same_1.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_vset_same_1", 0), self.dut.GetDPIHandle("WayLookup_vset_same_1", 1))
        self.WayLookup_vset_same_2.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_vset_same_2", 0), self.dut.GetDPIHandle("WayLookup_vset_same_2", 1))
        self.WayLookup_vset_same_3.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_vset_same_3", 0), self.dut.GetDPIHandle("WayLookup_vset_same_3", 1))
        self.WayLookup_vset_same_4.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_vset_same_4", 0), self.dut.GetDPIHandle("WayLookup_vset_same_4", 1))
        self.WayLookup_vset_same_5.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_vset_same_5", 0), self.dut.GetDPIHandle("WayLookup_vset_same_5", 1))
        self.WayLookup_vset_same_6.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_vset_same_6", 0), self.dut.GetDPIHandle("WayLookup_vset_same_6", 1))
        self.WayLookup_vset_same_7.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_vset_same_7", 0), self.dut.GetDPIHandle("WayLookup_vset_same_7", 1))
        self.WayLookup_vset_same_8.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_vset_same_8", 0), self.dut.GetDPIHandle("WayLookup_vset_same_8", 1))
        self.WayLookup_vset_same_9.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_vset_same_9", 0), self.dut.GetDPIHandle("WayLookup_vset_same_9", 1))
        self.WayLookup_vset_same_10.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_vset_same_10", 0), self.dut.GetDPIHandle("WayLookup_vset_same_10", 1))
        self.WayLookup_vset_same_11.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_vset_same_11", 0), self.dut.GetDPIHandle("WayLookup_vset_same_11", 1))
        self.WayLookup_vset_same_12.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_vset_same_12", 0), self.dut.GetDPIHandle("WayLookup_vset_same_12", 1))
        self.WayLookup_vset_same_13.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_vset_same_13", 0), self.dut.GetDPIHandle("WayLookup_vset_same_13", 1))
        self.WayLookup_vset_same_14.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_vset_same_14", 0), self.dut.GetDPIHandle("WayLookup_vset_same_14", 1))
        self.WayLookup_vset_same_15.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_vset_same_15", 0), self.dut.GetDPIHandle("WayLookup_vset_same_15", 1))
        self.WayLookup_vset_same_16.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_vset_same_16", 0), self.dut.GetDPIHandle("WayLookup_vset_same_16", 1))
        self.WayLookup_vset_same_17.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_vset_same_17", 0), self.dut.GetDPIHandle("WayLookup_vset_same_17", 1))
        self.WayLookup_vset_same_18.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_vset_same_18", 0), self.dut.GetDPIHandle("WayLookup_vset_same_18", 1))
        self.WayLookup_vset_same_19.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_vset_same_19", 0), self.dut.GetDPIHandle("WayLookup_vset_same_19", 1))
        self.WayLookup_vset_same_20.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_vset_same_20", 0), self.dut.GetDPIHandle("WayLookup_vset_same_20", 1))
        self.WayLookup_vset_same_21.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_vset_same_21", 0), self.dut.GetDPIHandle("WayLookup_vset_same_21", 1))
        self.WayLookup_vset_same_22.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_vset_same_22", 0), self.dut.GetDPIHandle("WayLookup_vset_same_22", 1))
        self.WayLookup_vset_same_23.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_vset_same_23", 0), self.dut.GetDPIHandle("WayLookup_vset_same_23", 1))
        self.WayLookup_vset_same_24.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_vset_same_24", 0), self.dut.GetDPIHandle("WayLookup_vset_same_24", 1))
        self.WayLookup_vset_same_25.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_vset_same_25", 0), self.dut.GetDPIHandle("WayLookup_vset_same_25", 1))
        self.WayLookup_vset_same_26.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_vset_same_26", 0), self.dut.GetDPIHandle("WayLookup_vset_same_26", 1))
        self.WayLookup_vset_same_27.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_vset_same_27", 0), self.dut.GetDPIHandle("WayLookup_vset_same_27", 1))
        self.WayLookup_vset_same_28.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_vset_same_28", 0), self.dut.GetDPIHandle("WayLookup_vset_same_28", 1))
        self.WayLookup_vset_same_29.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_vset_same_29", 0), self.dut.GetDPIHandle("WayLookup_vset_same_29", 1))
        self.WayLookup_vset_same_30.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_vset_same_30", 0), self.dut.GetDPIHandle("WayLookup_vset_same_30", 1))
        self.WayLookup_vset_same_31.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_vset_same_31", 0), self.dut.GetDPIHandle("WayLookup_vset_same_31", 1))
        self.WayLookup_vset_same_32.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_vset_same_32", 0), self.dut.GetDPIHandle("WayLookup_vset_same_32", 1))
        self.WayLookup_vset_same_33.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_vset_same_33", 0), self.dut.GetDPIHandle("WayLookup_vset_same_33", 1))
        self.WayLookup_vset_same_34.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_vset_same_34", 0), self.dut.GetDPIHandle("WayLookup_vset_same_34", 1))
        self.WayLookup_vset_same_35.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_vset_same_35", 0), self.dut.GetDPIHandle("WayLookup_vset_same_35", 1))
        self.WayLookup_vset_same_36.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_vset_same_36", 0), self.dut.GetDPIHandle("WayLookup_vset_same_36", 1))
        self.WayLookup_vset_same_37.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_vset_same_37", 0), self.dut.GetDPIHandle("WayLookup_vset_same_37", 1))
        self.WayLookup_vset_same_38.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_vset_same_38", 0), self.dut.GetDPIHandle("WayLookup_vset_same_38", 1))
        self.WayLookup_vset_same_39.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_vset_same_39", 0), self.dut.GetDPIHandle("WayLookup_vset_same_39", 1))
        self.WayLookup_vset_same_40.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_vset_same_40", 0), self.dut.GetDPIHandle("WayLookup_vset_same_40", 1))
        self.WayLookup_vset_same_41.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_vset_same_41", 0), self.dut.GetDPIHandle("WayLookup_vset_same_41", 1))
        self.WayLookup_vset_same_42.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_vset_same_42", 0), self.dut.GetDPIHandle("WayLookup_vset_same_42", 1))
        self.WayLookup_vset_same_43.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_vset_same_43", 0), self.dut.GetDPIHandle("WayLookup_vset_same_43", 1))
        self.WayLookup_vset_same_44.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_vset_same_44", 0), self.dut.GetDPIHandle("WayLookup_vset_same_44", 1))
        self.WayLookup_vset_same_45.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_vset_same_45", 0), self.dut.GetDPIHandle("WayLookup_vset_same_45", 1))
        self.WayLookup_vset_same_46.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_vset_same_46", 0), self.dut.GetDPIHandle("WayLookup_vset_same_46", 1))
        self.WayLookup_vset_same_47.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_vset_same_47", 0), self.dut.GetDPIHandle("WayLookup_vset_same_47", 1))
        self.WayLookup_vset_same_48.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_vset_same_48", 0), self.dut.GetDPIHandle("WayLookup_vset_same_48", 1))
        self.WayLookup_vset_same_49.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_vset_same_49", 0), self.dut.GetDPIHandle("WayLookup_vset_same_49", 1))
        self.WayLookup_vset_same_50.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_vset_same_50", 0), self.dut.GetDPIHandle("WayLookup_vset_same_50", 1))
        self.WayLookup_vset_same_51.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_vset_same_51", 0), self.dut.GetDPIHandle("WayLookup_vset_same_51", 1))
        self.WayLookup_vset_same_52.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_vset_same_52", 0), self.dut.GetDPIHandle("WayLookup_vset_same_52", 1))
        self.WayLookup_vset_same_53.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_vset_same_53", 0), self.dut.GetDPIHandle("WayLookup_vset_same_53", 1))
        self.WayLookup_vset_same_54.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_vset_same_54", 0), self.dut.GetDPIHandle("WayLookup_vset_same_54", 1))
        self.WayLookup_vset_same_55.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_vset_same_55", 0), self.dut.GetDPIHandle("WayLookup_vset_same_55", 1))
        self.WayLookup_vset_same_56.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_vset_same_56", 0), self.dut.GetDPIHandle("WayLookup_vset_same_56", 1))
        self.WayLookup_vset_same_57.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_vset_same_57", 0), self.dut.GetDPIHandle("WayLookup_vset_same_57", 1))
        self.WayLookup_vset_same_58.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_vset_same_58", 0), self.dut.GetDPIHandle("WayLookup_vset_same_58", 1))
        self.WayLookup_vset_same_59.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_vset_same_59", 0), self.dut.GetDPIHandle("WayLookup_vset_same_59", 1))
        self.WayLookup_vset_same_60.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_vset_same_60", 0), self.dut.GetDPIHandle("WayLookup_vset_same_60", 1))
        self.WayLookup_vset_same_61.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_vset_same_61", 0), self.dut.GetDPIHandle("WayLookup_vset_same_61", 1))
        self.WayLookup_vset_same_62.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_vset_same_62", 0), self.dut.GetDPIHandle("WayLookup_vset_same_62", 1))
        self.WayLookup_vset_same_63.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_vset_same_63", 0), self.dut.GetDPIHandle("WayLookup_vset_same_63", 1))
        self.WayLookup_ptag_same.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_ptag_same", 0), self.dut.GetDPIHandle("WayLookup_ptag_same", 1))
        self.WayLookup_ptag_same_1.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_ptag_same_1", 0), self.dut.GetDPIHandle("WayLookup_ptag_same_1", 1))
        self.WayLookup_ptag_same_2.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_ptag_same_2", 0), self.dut.GetDPIHandle("WayLookup_ptag_same_2", 1))
        self.WayLookup_ptag_same_3.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_ptag_same_3", 0), self.dut.GetDPIHandle("WayLookup_ptag_same_3", 1))
        self.WayLookup_ptag_same_4.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_ptag_same_4", 0), self.dut.GetDPIHandle("WayLookup_ptag_same_4", 1))
        self.WayLookup_ptag_same_5.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_ptag_same_5", 0), self.dut.GetDPIHandle("WayLookup_ptag_same_5", 1))
        self.WayLookup_ptag_same_6.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_ptag_same_6", 0), self.dut.GetDPIHandle("WayLookup_ptag_same_6", 1))
        self.WayLookup_ptag_same_7.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_ptag_same_7", 0), self.dut.GetDPIHandle("WayLookup_ptag_same_7", 1))
        self.WayLookup_ptag_same_8.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_ptag_same_8", 0), self.dut.GetDPIHandle("WayLookup_ptag_same_8", 1))
        self.WayLookup_ptag_same_9.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_ptag_same_9", 0), self.dut.GetDPIHandle("WayLookup_ptag_same_9", 1))
        self.WayLookup_ptag_same_10.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_ptag_same_10", 0), self.dut.GetDPIHandle("WayLookup_ptag_same_10", 1))
        self.WayLookup_ptag_same_11.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_ptag_same_11", 0), self.dut.GetDPIHandle("WayLookup_ptag_same_11", 1))
        self.WayLookup_ptag_same_12.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_ptag_same_12", 0), self.dut.GetDPIHandle("WayLookup_ptag_same_12", 1))
        self.WayLookup_ptag_same_13.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_ptag_same_13", 0), self.dut.GetDPIHandle("WayLookup_ptag_same_13", 1))
        self.WayLookup_ptag_same_14.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_ptag_same_14", 0), self.dut.GetDPIHandle("WayLookup_ptag_same_14", 1))
        self.WayLookup_ptag_same_15.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_ptag_same_15", 0), self.dut.GetDPIHandle("WayLookup_ptag_same_15", 1))
        self.WayLookup_ptag_same_16.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_ptag_same_16", 0), self.dut.GetDPIHandle("WayLookup_ptag_same_16", 1))
        self.WayLookup_ptag_same_17.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_ptag_same_17", 0), self.dut.GetDPIHandle("WayLookup_ptag_same_17", 1))
        self.WayLookup_ptag_same_18.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_ptag_same_18", 0), self.dut.GetDPIHandle("WayLookup_ptag_same_18", 1))
        self.WayLookup_ptag_same_19.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_ptag_same_19", 0), self.dut.GetDPIHandle("WayLookup_ptag_same_19", 1))
        self.WayLookup_ptag_same_20.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_ptag_same_20", 0), self.dut.GetDPIHandle("WayLookup_ptag_same_20", 1))
        self.WayLookup_ptag_same_21.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_ptag_same_21", 0), self.dut.GetDPIHandle("WayLookup_ptag_same_21", 1))
        self.WayLookup_ptag_same_22.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_ptag_same_22", 0), self.dut.GetDPIHandle("WayLookup_ptag_same_22", 1))
        self.WayLookup_ptag_same_23.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_ptag_same_23", 0), self.dut.GetDPIHandle("WayLookup_ptag_same_23", 1))
        self.WayLookup_ptag_same_24.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_ptag_same_24", 0), self.dut.GetDPIHandle("WayLookup_ptag_same_24", 1))
        self.WayLookup_ptag_same_25.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_ptag_same_25", 0), self.dut.GetDPIHandle("WayLookup_ptag_same_25", 1))
        self.WayLookup_ptag_same_26.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_ptag_same_26", 0), self.dut.GetDPIHandle("WayLookup_ptag_same_26", 1))
        self.WayLookup_ptag_same_27.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_ptag_same_27", 0), self.dut.GetDPIHandle("WayLookup_ptag_same_27", 1))
        self.WayLookup_ptag_same_28.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_ptag_same_28", 0), self.dut.GetDPIHandle("WayLookup_ptag_same_28", 1))
        self.WayLookup_ptag_same_29.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_ptag_same_29", 0), self.dut.GetDPIHandle("WayLookup_ptag_same_29", 1))
        self.WayLookup_ptag_same_30.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_ptag_same_30", 0), self.dut.GetDPIHandle("WayLookup_ptag_same_30", 1))
        self.WayLookup_ptag_same_31.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_ptag_same_31", 0), self.dut.GetDPIHandle("WayLookup_ptag_same_31", 1))
        self.WayLookup_ptag_same_32.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_ptag_same_32", 0), self.dut.GetDPIHandle("WayLookup_ptag_same_32", 1))
        self.WayLookup_ptag_same_33.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_ptag_same_33", 0), self.dut.GetDPIHandle("WayLookup_ptag_same_33", 1))
        self.WayLookup_ptag_same_34.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_ptag_same_34", 0), self.dut.GetDPIHandle("WayLookup_ptag_same_34", 1))
        self.WayLookup_ptag_same_35.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_ptag_same_35", 0), self.dut.GetDPIHandle("WayLookup_ptag_same_35", 1))
        self.WayLookup_ptag_same_36.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_ptag_same_36", 0), self.dut.GetDPIHandle("WayLookup_ptag_same_36", 1))
        self.WayLookup_ptag_same_37.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_ptag_same_37", 0), self.dut.GetDPIHandle("WayLookup_ptag_same_37", 1))
        self.WayLookup_ptag_same_38.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_ptag_same_38", 0), self.dut.GetDPIHandle("WayLookup_ptag_same_38", 1))
        self.WayLookup_ptag_same_39.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_ptag_same_39", 0), self.dut.GetDPIHandle("WayLookup_ptag_same_39", 1))
        self.WayLookup_ptag_same_40.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_ptag_same_40", 0), self.dut.GetDPIHandle("WayLookup_ptag_same_40", 1))
        self.WayLookup_ptag_same_41.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_ptag_same_41", 0), self.dut.GetDPIHandle("WayLookup_ptag_same_41", 1))
        self.WayLookup_ptag_same_42.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_ptag_same_42", 0), self.dut.GetDPIHandle("WayLookup_ptag_same_42", 1))
        self.WayLookup_ptag_same_43.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_ptag_same_43", 0), self.dut.GetDPIHandle("WayLookup_ptag_same_43", 1))
        self.WayLookup_ptag_same_44.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_ptag_same_44", 0), self.dut.GetDPIHandle("WayLookup_ptag_same_44", 1))
        self.WayLookup_ptag_same_45.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_ptag_same_45", 0), self.dut.GetDPIHandle("WayLookup_ptag_same_45", 1))
        self.WayLookup_ptag_same_46.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_ptag_same_46", 0), self.dut.GetDPIHandle("WayLookup_ptag_same_46", 1))
        self.WayLookup_ptag_same_47.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_ptag_same_47", 0), self.dut.GetDPIHandle("WayLookup_ptag_same_47", 1))
        self.WayLookup_ptag_same_48.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_ptag_same_48", 0), self.dut.GetDPIHandle("WayLookup_ptag_same_48", 1))
        self.WayLookup_ptag_same_49.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_ptag_same_49", 0), self.dut.GetDPIHandle("WayLookup_ptag_same_49", 1))
        self.WayLookup_ptag_same_50.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_ptag_same_50", 0), self.dut.GetDPIHandle("WayLookup_ptag_same_50", 1))
        self.WayLookup_ptag_same_51.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_ptag_same_51", 0), self.dut.GetDPIHandle("WayLookup_ptag_same_51", 1))
        self.WayLookup_ptag_same_52.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_ptag_same_52", 0), self.dut.GetDPIHandle("WayLookup_ptag_same_52", 1))
        self.WayLookup_ptag_same_53.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_ptag_same_53", 0), self.dut.GetDPIHandle("WayLookup_ptag_same_53", 1))
        self.WayLookup_ptag_same_54.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_ptag_same_54", 0), self.dut.GetDPIHandle("WayLookup_ptag_same_54", 1))
        self.WayLookup_ptag_same_55.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_ptag_same_55", 0), self.dut.GetDPIHandle("WayLookup_ptag_same_55", 1))
        self.WayLookup_ptag_same_56.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_ptag_same_56", 0), self.dut.GetDPIHandle("WayLookup_ptag_same_56", 1))
        self.WayLookup_ptag_same_57.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_ptag_same_57", 0), self.dut.GetDPIHandle("WayLookup_ptag_same_57", 1))
        self.WayLookup_ptag_same_58.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_ptag_same_58", 0), self.dut.GetDPIHandle("WayLookup_ptag_same_58", 1))
        self.WayLookup_ptag_same_59.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_ptag_same_59", 0), self.dut.GetDPIHandle("WayLookup_ptag_same_59", 1))
        self.WayLookup_ptag_same_60.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_ptag_same_60", 0), self.dut.GetDPIHandle("WayLookup_ptag_same_60", 1))
        self.WayLookup_ptag_same_61.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_ptag_same_61", 0), self.dut.GetDPIHandle("WayLookup_ptag_same_61", 1))
        self.WayLookup_ptag_same_62.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_ptag_same_62", 0), self.dut.GetDPIHandle("WayLookup_ptag_same_62", 1))
        self.WayLookup_ptag_same_63.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_ptag_same_63", 0), self.dut.GetDPIHandle("WayLookup_ptag_same_63", 1))
        self.WayLookup_entries_0_waymask_0.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_entries_0_waymask_0", 0), self.dut.GetDPIHandle("WayLookup_entries_0_waymask_0", 1))
        self.WayLookup_entries_0_waymask_1.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_entries_0_waymask_1", 0), self.dut.GetDPIHandle("WayLookup_entries_0_waymask_1", 1))
        self.WayLookup_entries_1_waymask_0.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_entries_1_waymask_0", 0), self.dut.GetDPIHandle("WayLookup_entries_1_waymask_0", 1))
        self.WayLookup_entries_1_waymask_1.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_entries_1_waymask_1", 0), self.dut.GetDPIHandle("WayLookup_entries_1_waymask_1", 1))
        self.WayLookup_entries_2_waymask_0.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_entries_2_waymask_0", 0), self.dut.GetDPIHandle("WayLookup_entries_2_waymask_0", 1))
        self.WayLookup_entries_2_waymask_1.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_entries_2_waymask_1", 0), self.dut.GetDPIHandle("WayLookup_entries_2_waymask_1", 1))
        self.WayLookup_entries_3_waymask_0.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_entries_3_waymask_0", 0), self.dut.GetDPIHandle("WayLookup_entries_3_waymask_0", 1))
        self.WayLookup_entries_3_waymask_1.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_entries_3_waymask_1", 0), self.dut.GetDPIHandle("WayLookup_entries_3_waymask_1", 1))
        self.WayLookup_entries_4_waymask_0.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_entries_4_waymask_0", 0), self.dut.GetDPIHandle("WayLookup_entries_4_waymask_0", 1))
        self.WayLookup_entries_4_waymask_1.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_entries_4_waymask_1", 0), self.dut.GetDPIHandle("WayLookup_entries_4_waymask_1", 1))
        self.WayLookup_entries_5_waymask_0.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_entries_5_waymask_0", 0), self.dut.GetDPIHandle("WayLookup_entries_5_waymask_0", 1))
        self.WayLookup_entries_5_waymask_1.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_entries_5_waymask_1", 0), self.dut.GetDPIHandle("WayLookup_entries_5_waymask_1", 1))
        self.WayLookup_entries_6_waymask_0.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_entries_6_waymask_0", 0), self.dut.GetDPIHandle("WayLookup_entries_6_waymask_0", 1))
        self.WayLookup_entries_6_waymask_1.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_entries_6_waymask_1", 0), self.dut.GetDPIHandle("WayLookup_entries_6_waymask_1", 1))
        self.WayLookup_entries_7_waymask_0.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_entries_7_waymask_0", 0), self.dut.GetDPIHandle("WayLookup_entries_7_waymask_0", 1))
        self.WayLookup_entries_7_waymask_1.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_entries_7_waymask_1", 0), self.dut.GetDPIHandle("WayLookup_entries_7_waymask_1", 1))
        self.WayLookup_entries_8_waymask_0.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_entries_8_waymask_0", 0), self.dut.GetDPIHandle("WayLookup_entries_8_waymask_0", 1))
        self.WayLookup_entries_8_waymask_1.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_entries_8_waymask_1", 0), self.dut.GetDPIHandle("WayLookup_entries_8_waymask_1", 1))
        self.WayLookup_entries_9_waymask_0.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_entries_9_waymask_0", 0), self.dut.GetDPIHandle("WayLookup_entries_9_waymask_0", 1))
        self.WayLookup_entries_9_waymask_1.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_entries_9_waymask_1", 0), self.dut.GetDPIHandle("WayLookup_entries_9_waymask_1", 1))
        self.WayLookup_entries_10_waymask_0.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_entries_10_waymask_0", 0), self.dut.GetDPIHandle("WayLookup_entries_10_waymask_0", 1))
        self.WayLookup_entries_10_waymask_1.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_entries_10_waymask_1", 0), self.dut.GetDPIHandle("WayLookup_entries_10_waymask_1", 1))
        self.WayLookup_entries_11_waymask_0.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_entries_11_waymask_0", 0), self.dut.GetDPIHandle("WayLookup_entries_11_waymask_0", 1))
        self.WayLookup_entries_11_waymask_1.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_entries_11_waymask_1", 0), self.dut.GetDPIHandle("WayLookup_entries_11_waymask_1", 1))
        self.WayLookup_entries_12_waymask_0.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_entries_12_waymask_0", 0), self.dut.GetDPIHandle("WayLookup_entries_12_waymask_0", 1))
        self.WayLookup_entries_12_waymask_1.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_entries_12_waymask_1", 0), self.dut.GetDPIHandle("WayLookup_entries_12_waymask_1", 1))
        self.WayLookup_entries_13_waymask_0.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_entries_13_waymask_0", 0), self.dut.GetDPIHandle("WayLookup_entries_13_waymask_0", 1))
        self.WayLookup_entries_13_waymask_1.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_entries_13_waymask_1", 0), self.dut.GetDPIHandle("WayLookup_entries_13_waymask_1", 1))
        self.WayLookup_entries_14_waymask_0.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_entries_14_waymask_0", 0), self.dut.GetDPIHandle("WayLookup_entries_14_waymask_0", 1))
        self.WayLookup_entries_14_waymask_1.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_entries_14_waymask_1", 0), self.dut.GetDPIHandle("WayLookup_entries_14_waymask_1", 1))
        self.WayLookup_entries_15_waymask_0.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_entries_15_waymask_0", 0), self.dut.GetDPIHandle("WayLookup_entries_15_waymask_0", 1))
        self.WayLookup_entries_15_waymask_1.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_entries_15_waymask_1", 0), self.dut.GetDPIHandle("WayLookup_entries_15_waymask_1", 1))
        self.WayLookup_entries_16_waymask_0.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_entries_16_waymask_0", 0), self.dut.GetDPIHandle("WayLookup_entries_16_waymask_0", 1))
        self.WayLookup_entries_16_waymask_1.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_entries_16_waymask_1", 0), self.dut.GetDPIHandle("WayLookup_entries_16_waymask_1", 1))
        self.WayLookup_entries_17_waymask_0.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_entries_17_waymask_0", 0), self.dut.GetDPIHandle("WayLookup_entries_17_waymask_0", 1))
        self.WayLookup_entries_17_waymask_1.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_entries_17_waymask_1", 0), self.dut.GetDPIHandle("WayLookup_entries_17_waymask_1", 1))
        self.WayLookup_entries_18_waymask_0.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_entries_18_waymask_0", 0), self.dut.GetDPIHandle("WayLookup_entries_18_waymask_0", 1))
        self.WayLookup_entries_18_waymask_1.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_entries_18_waymask_1", 0), self.dut.GetDPIHandle("WayLookup_entries_18_waymask_1", 1))
        self.WayLookup_entries_19_waymask_0.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_entries_19_waymask_0", 0), self.dut.GetDPIHandle("WayLookup_entries_19_waymask_0", 1))
        self.WayLookup_entries_19_waymask_1.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_entries_19_waymask_1", 0), self.dut.GetDPIHandle("WayLookup_entries_19_waymask_1", 1))
        self.WayLookup_entries_20_waymask_0.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_entries_20_waymask_0", 0), self.dut.GetDPIHandle("WayLookup_entries_20_waymask_0", 1))
        self.WayLookup_entries_20_waymask_1.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_entries_20_waymask_1", 0), self.dut.GetDPIHandle("WayLookup_entries_20_waymask_1", 1))
        self.WayLookup_entries_21_waymask_0.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_entries_21_waymask_0", 0), self.dut.GetDPIHandle("WayLookup_entries_21_waymask_0", 1))
        self.WayLookup_entries_21_waymask_1.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_entries_21_waymask_1", 0), self.dut.GetDPIHandle("WayLookup_entries_21_waymask_1", 1))
        self.WayLookup_entries_22_waymask_0.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_entries_22_waymask_0", 0), self.dut.GetDPIHandle("WayLookup_entries_22_waymask_0", 1))
        self.WayLookup_entries_22_waymask_1.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_entries_22_waymask_1", 0), self.dut.GetDPIHandle("WayLookup_entries_22_waymask_1", 1))
        self.WayLookup_entries_23_waymask_0.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_entries_23_waymask_0", 0), self.dut.GetDPIHandle("WayLookup_entries_23_waymask_0", 1))
        self.WayLookup_entries_23_waymask_1.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_entries_23_waymask_1", 0), self.dut.GetDPIHandle("WayLookup_entries_23_waymask_1", 1))
        self.WayLookup_entries_24_waymask_0.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_entries_24_waymask_0", 0), self.dut.GetDPIHandle("WayLookup_entries_24_waymask_0", 1))
        self.WayLookup_entries_24_waymask_1.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_entries_24_waymask_1", 0), self.dut.GetDPIHandle("WayLookup_entries_24_waymask_1", 1))
        self.WayLookup_entries_25_waymask_0.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_entries_25_waymask_0", 0), self.dut.GetDPIHandle("WayLookup_entries_25_waymask_0", 1))
        self.WayLookup_entries_25_waymask_1.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_entries_25_waymask_1", 0), self.dut.GetDPIHandle("WayLookup_entries_25_waymask_1", 1))
        self.WayLookup_entries_26_waymask_0.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_entries_26_waymask_0", 0), self.dut.GetDPIHandle("WayLookup_entries_26_waymask_0", 1))
        self.WayLookup_entries_26_waymask_1.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_entries_26_waymask_1", 0), self.dut.GetDPIHandle("WayLookup_entries_26_waymask_1", 1))
        self.WayLookup_entries_27_waymask_0.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_entries_27_waymask_0", 0), self.dut.GetDPIHandle("WayLookup_entries_27_waymask_0", 1))
        self.WayLookup_entries_27_waymask_1.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_entries_27_waymask_1", 0), self.dut.GetDPIHandle("WayLookup_entries_27_waymask_1", 1))
        self.WayLookup_entries_28_waymask_0.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_entries_28_waymask_0", 0), self.dut.GetDPIHandle("WayLookup_entries_28_waymask_0", 1))
        self.WayLookup_entries_28_waymask_1.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_entries_28_waymask_1", 0), self.dut.GetDPIHandle("WayLookup_entries_28_waymask_1", 1))
        self.WayLookup_entries_29_waymask_0.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_entries_29_waymask_0", 0), self.dut.GetDPIHandle("WayLookup_entries_29_waymask_0", 1))
        self.WayLookup_entries_29_waymask_1.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_entries_29_waymask_1", 0), self.dut.GetDPIHandle("WayLookup_entries_29_waymask_1", 1))
        self.WayLookup_entries_30_waymask_0.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_entries_30_waymask_0", 0), self.dut.GetDPIHandle("WayLookup_entries_30_waymask_0", 1))
        self.WayLookup_entries_30_waymask_1.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_entries_30_waymask_1", 0), self.dut.GetDPIHandle("WayLookup_entries_30_waymask_1", 1))
        self.WayLookup_entries_31_waymask_0.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_entries_31_waymask_0", 0), self.dut.GetDPIHandle("WayLookup_entries_31_waymask_0", 1))
        self.WayLookup_entries_31_waymask_1.BindDPIPtr(self.dut.GetDPIHandle("WayLookup_entries_31_waymask_1", 0), self.dut.GetDPIHandle("WayLookup_entries_31_waymask_1", 1))


        # Add2Port
        self.xport.Add("clock", self.clock.xdata)
        self.xport.Add("reset", self.reset.xdata)
        self.xport.Add("io_flush", self.io_flush.xdata)
        self.xport.Add("io_read_ready", self.io_read_ready.xdata)
        self.xport.Add("io_read_valid", self.io_read_valid.xdata)
        self.xport.Add("io_read_bits_entry_vSetIdx_0", self.io_read_bits_entry_vSetIdx_0.xdata)
        self.xport.Add("io_read_bits_entry_vSetIdx_1", self.io_read_bits_entry_vSetIdx_1.xdata)
        self.xport.Add("io_read_bits_entry_waymask_0", self.io_read_bits_entry_waymask_0.xdata)
        self.xport.Add("io_read_bits_entry_waymask_1", self.io_read_bits_entry_waymask_1.xdata)
        self.xport.Add("io_read_bits_entry_ptag_0", self.io_read_bits_entry_ptag_0.xdata)
        self.xport.Add("io_read_bits_entry_ptag_1", self.io_read_bits_entry_ptag_1.xdata)
        self.xport.Add("io_read_bits_entry_itlb_exception_0", self.io_read_bits_entry_itlb_exception_0.xdata)
        self.xport.Add("io_read_bits_entry_itlb_exception_1", self.io_read_bits_entry_itlb_exception_1.xdata)
        self.xport.Add("io_read_bits_entry_itlb_pbmt_0", self.io_read_bits_entry_itlb_pbmt_0.xdata)
        self.xport.Add("io_read_bits_entry_itlb_pbmt_1", self.io_read_bits_entry_itlb_pbmt_1.xdata)
        self.xport.Add("io_read_bits_entry_meta_codes_0", self.io_read_bits_entry_meta_codes_0.xdata)
        self.xport.Add("io_read_bits_entry_meta_codes_1", self.io_read_bits_entry_meta_codes_1.xdata)
        self.xport.Add("io_read_bits_gpf_gpaddr", self.io_read_bits_gpf_gpaddr.xdata)
        self.xport.Add("io_read_bits_gpf_isForVSnonLeafPTE", self.io_read_bits_gpf_isForVSnonLeafPTE.xdata)
        self.xport.Add("io_write_ready", self.io_write_ready.xdata)
        self.xport.Add("io_write_valid", self.io_write_valid.xdata)
        self.xport.Add("io_write_bits_entry_vSetIdx_0", self.io_write_bits_entry_vSetIdx_0.xdata)
        self.xport.Add("io_write_bits_entry_vSetIdx_1", self.io_write_bits_entry_vSetIdx_1.xdata)
        self.xport.Add("io_write_bits_entry_waymask_0", self.io_write_bits_entry_waymask_0.xdata)
        self.xport.Add("io_write_bits_entry_waymask_1", self.io_write_bits_entry_waymask_1.xdata)
        self.xport.Add("io_write_bits_entry_ptag_0", self.io_write_bits_entry_ptag_0.xdata)
        self.xport.Add("io_write_bits_entry_ptag_1", self.io_write_bits_entry_ptag_1.xdata)
        self.xport.Add("io_write_bits_entry_itlb_exception_0", self.io_write_bits_entry_itlb_exception_0.xdata)
        self.xport.Add("io_write_bits_entry_itlb_exception_1", self.io_write_bits_entry_itlb_exception_1.xdata)
        self.xport.Add("io_write_bits_entry_itlb_pbmt_0", self.io_write_bits_entry_itlb_pbmt_0.xdata)
        self.xport.Add("io_write_bits_entry_itlb_pbmt_1", self.io_write_bits_entry_itlb_pbmt_1.xdata)
        self.xport.Add("io_write_bits_entry_meta_codes_0", self.io_write_bits_entry_meta_codes_0.xdata)
        self.xport.Add("io_write_bits_entry_meta_codes_1", self.io_write_bits_entry_meta_codes_1.xdata)
        self.xport.Add("io_write_bits_gpf_gpaddr", self.io_write_bits_gpf_gpaddr.xdata)
        self.xport.Add("io_write_bits_gpf_isForVSnonLeafPTE", self.io_write_bits_gpf_isForVSnonLeafPTE.xdata)
        self.xport.Add("io_update_valid", self.io_update_valid.xdata)
        self.xport.Add("io_update_bits_blkPaddr", self.io_update_bits_blkPaddr.xdata)
        self.xport.Add("io_update_bits_vSetIdx", self.io_update_bits_vSetIdx.xdata)
        self.xport.Add("io_update_bits_waymask", self.io_update_bits_waymask.xdata)
        self.xport.Add("io_update_bits_corrupt", self.io_update_bits_corrupt.xdata)
        self.xport.Add("WayLookup_readPtr_flag", self.WayLookup_readPtr_flag.xdata)
        self.xport.Add("WayLookup_readPtr_value", self.WayLookup_readPtr_value.xdata)
        self.xport.Add("WayLookup_writePtr_flag", self.WayLookup_writePtr_flag.xdata)
        self.xport.Add("WayLookup_writePtr_value", self.WayLookup_writePtr_value.xdata)
        self.xport.Add("WayLookup_gpf_hit", self.WayLookup_gpf_hit.xdata)
        self.xport.Add("WayLookup_gpf_entry_valid", self.WayLookup_gpf_entry_valid.xdata)
        self.xport.Add("WayLookup_gpf_entry_bits_gpaddr", self.WayLookup_gpf_entry_bits_gpaddr.xdata)
        self.xport.Add("WayLookup_entries_0_vSetIdx_0", self.WayLookup_entries_0_vSetIdx_0.xdata)
        self.xport.Add("WayLookup_entries_0_vSetIdx_1", self.WayLookup_entries_0_vSetIdx_1.xdata)
        self.xport.Add("WayLookup_entries_0_ptag_0", self.WayLookup_entries_0_ptag_0.xdata)
        self.xport.Add("WayLookup_entries_0_ptag_1", self.WayLookup_entries_0_ptag_1.xdata)
        self.xport.Add("WayLookup_entries_0_itlb_exception_0", self.WayLookup_entries_0_itlb_exception_0.xdata)
        self.xport.Add("WayLookup_entries_0_itlb_exception_1", self.WayLookup_entries_0_itlb_exception_1.xdata)
        self.xport.Add("WayLookup_entries_0_itlb_pbmt_0", self.WayLookup_entries_0_itlb_pbmt_0.xdata)
        self.xport.Add("WayLookup_entries_0_itlb_pbmt_1", self.WayLookup_entries_0_itlb_pbmt_1.xdata)
        self.xport.Add("WayLookup_entries_0_meta_codes_0", self.WayLookup_entries_0_meta_codes_0.xdata)
        self.xport.Add("WayLookup_entries_0_meta_codes_1", self.WayLookup_entries_0_meta_codes_1.xdata)
        self.xport.Add("WayLookup_vset_same", self.WayLookup_vset_same.xdata)
        self.xport.Add("WayLookup_vset_same_1", self.WayLookup_vset_same_1.xdata)
        self.xport.Add("WayLookup_vset_same_2", self.WayLookup_vset_same_2.xdata)
        self.xport.Add("WayLookup_vset_same_3", self.WayLookup_vset_same_3.xdata)
        self.xport.Add("WayLookup_vset_same_4", self.WayLookup_vset_same_4.xdata)
        self.xport.Add("WayLookup_vset_same_5", self.WayLookup_vset_same_5.xdata)
        self.xport.Add("WayLookup_vset_same_6", self.WayLookup_vset_same_6.xdata)
        self.xport.Add("WayLookup_vset_same_7", self.WayLookup_vset_same_7.xdata)
        self.xport.Add("WayLookup_vset_same_8", self.WayLookup_vset_same_8.xdata)
        self.xport.Add("WayLookup_vset_same_9", self.WayLookup_vset_same_9.xdata)
        self.xport.Add("WayLookup_vset_same_10", self.WayLookup_vset_same_10.xdata)
        self.xport.Add("WayLookup_vset_same_11", self.WayLookup_vset_same_11.xdata)
        self.xport.Add("WayLookup_vset_same_12", self.WayLookup_vset_same_12.xdata)
        self.xport.Add("WayLookup_vset_same_13", self.WayLookup_vset_same_13.xdata)
        self.xport.Add("WayLookup_vset_same_14", self.WayLookup_vset_same_14.xdata)
        self.xport.Add("WayLookup_vset_same_15", self.WayLookup_vset_same_15.xdata)
        self.xport.Add("WayLookup_vset_same_16", self.WayLookup_vset_same_16.xdata)
        self.xport.Add("WayLookup_vset_same_17", self.WayLookup_vset_same_17.xdata)
        self.xport.Add("WayLookup_vset_same_18", self.WayLookup_vset_same_18.xdata)
        self.xport.Add("WayLookup_vset_same_19", self.WayLookup_vset_same_19.xdata)
        self.xport.Add("WayLookup_vset_same_20", self.WayLookup_vset_same_20.xdata)
        self.xport.Add("WayLookup_vset_same_21", self.WayLookup_vset_same_21.xdata)
        self.xport.Add("WayLookup_vset_same_22", self.WayLookup_vset_same_22.xdata)
        self.xport.Add("WayLookup_vset_same_23", self.WayLookup_vset_same_23.xdata)
        self.xport.Add("WayLookup_vset_same_24", self.WayLookup_vset_same_24.xdata)
        self.xport.Add("WayLookup_vset_same_25", self.WayLookup_vset_same_25.xdata)
        self.xport.Add("WayLookup_vset_same_26", self.WayLookup_vset_same_26.xdata)
        self.xport.Add("WayLookup_vset_same_27", self.WayLookup_vset_same_27.xdata)
        self.xport.Add("WayLookup_vset_same_28", self.WayLookup_vset_same_28.xdata)
        self.xport.Add("WayLookup_vset_same_29", self.WayLookup_vset_same_29.xdata)
        self.xport.Add("WayLookup_vset_same_30", self.WayLookup_vset_same_30.xdata)
        self.xport.Add("WayLookup_vset_same_31", self.WayLookup_vset_same_31.xdata)
        self.xport.Add("WayLookup_vset_same_32", self.WayLookup_vset_same_32.xdata)
        self.xport.Add("WayLookup_vset_same_33", self.WayLookup_vset_same_33.xdata)
        self.xport.Add("WayLookup_vset_same_34", self.WayLookup_vset_same_34.xdata)
        self.xport.Add("WayLookup_vset_same_35", self.WayLookup_vset_same_35.xdata)
        self.xport.Add("WayLookup_vset_same_36", self.WayLookup_vset_same_36.xdata)
        self.xport.Add("WayLookup_vset_same_37", self.WayLookup_vset_same_37.xdata)
        self.xport.Add("WayLookup_vset_same_38", self.WayLookup_vset_same_38.xdata)
        self.xport.Add("WayLookup_vset_same_39", self.WayLookup_vset_same_39.xdata)
        self.xport.Add("WayLookup_vset_same_40", self.WayLookup_vset_same_40.xdata)
        self.xport.Add("WayLookup_vset_same_41", self.WayLookup_vset_same_41.xdata)
        self.xport.Add("WayLookup_vset_same_42", self.WayLookup_vset_same_42.xdata)
        self.xport.Add("WayLookup_vset_same_43", self.WayLookup_vset_same_43.xdata)
        self.xport.Add("WayLookup_vset_same_44", self.WayLookup_vset_same_44.xdata)
        self.xport.Add("WayLookup_vset_same_45", self.WayLookup_vset_same_45.xdata)
        self.xport.Add("WayLookup_vset_same_46", self.WayLookup_vset_same_46.xdata)
        self.xport.Add("WayLookup_vset_same_47", self.WayLookup_vset_same_47.xdata)
        self.xport.Add("WayLookup_vset_same_48", self.WayLookup_vset_same_48.xdata)
        self.xport.Add("WayLookup_vset_same_49", self.WayLookup_vset_same_49.xdata)
        self.xport.Add("WayLookup_vset_same_50", self.WayLookup_vset_same_50.xdata)
        self.xport.Add("WayLookup_vset_same_51", self.WayLookup_vset_same_51.xdata)
        self.xport.Add("WayLookup_vset_same_52", self.WayLookup_vset_same_52.xdata)
        self.xport.Add("WayLookup_vset_same_53", self.WayLookup_vset_same_53.xdata)
        self.xport.Add("WayLookup_vset_same_54", self.WayLookup_vset_same_54.xdata)
        self.xport.Add("WayLookup_vset_same_55", self.WayLookup_vset_same_55.xdata)
        self.xport.Add("WayLookup_vset_same_56", self.WayLookup_vset_same_56.xdata)
        self.xport.Add("WayLookup_vset_same_57", self.WayLookup_vset_same_57.xdata)
        self.xport.Add("WayLookup_vset_same_58", self.WayLookup_vset_same_58.xdata)
        self.xport.Add("WayLookup_vset_same_59", self.WayLookup_vset_same_59.xdata)
        self.xport.Add("WayLookup_vset_same_60", self.WayLookup_vset_same_60.xdata)
        self.xport.Add("WayLookup_vset_same_61", self.WayLookup_vset_same_61.xdata)
        self.xport.Add("WayLookup_vset_same_62", self.WayLookup_vset_same_62.xdata)
        self.xport.Add("WayLookup_vset_same_63", self.WayLookup_vset_same_63.xdata)
        self.xport.Add("WayLookup_ptag_same", self.WayLookup_ptag_same.xdata)
        self.xport.Add("WayLookup_ptag_same_1", self.WayLookup_ptag_same_1.xdata)
        self.xport.Add("WayLookup_ptag_same_2", self.WayLookup_ptag_same_2.xdata)
        self.xport.Add("WayLookup_ptag_same_3", self.WayLookup_ptag_same_3.xdata)
        self.xport.Add("WayLookup_ptag_same_4", self.WayLookup_ptag_same_4.xdata)
        self.xport.Add("WayLookup_ptag_same_5", self.WayLookup_ptag_same_5.xdata)
        self.xport.Add("WayLookup_ptag_same_6", self.WayLookup_ptag_same_6.xdata)
        self.xport.Add("WayLookup_ptag_same_7", self.WayLookup_ptag_same_7.xdata)
        self.xport.Add("WayLookup_ptag_same_8", self.WayLookup_ptag_same_8.xdata)
        self.xport.Add("WayLookup_ptag_same_9", self.WayLookup_ptag_same_9.xdata)
        self.xport.Add("WayLookup_ptag_same_10", self.WayLookup_ptag_same_10.xdata)
        self.xport.Add("WayLookup_ptag_same_11", self.WayLookup_ptag_same_11.xdata)
        self.xport.Add("WayLookup_ptag_same_12", self.WayLookup_ptag_same_12.xdata)
        self.xport.Add("WayLookup_ptag_same_13", self.WayLookup_ptag_same_13.xdata)
        self.xport.Add("WayLookup_ptag_same_14", self.WayLookup_ptag_same_14.xdata)
        self.xport.Add("WayLookup_ptag_same_15", self.WayLookup_ptag_same_15.xdata)
        self.xport.Add("WayLookup_ptag_same_16", self.WayLookup_ptag_same_16.xdata)
        self.xport.Add("WayLookup_ptag_same_17", self.WayLookup_ptag_same_17.xdata)
        self.xport.Add("WayLookup_ptag_same_18", self.WayLookup_ptag_same_18.xdata)
        self.xport.Add("WayLookup_ptag_same_19", self.WayLookup_ptag_same_19.xdata)
        self.xport.Add("WayLookup_ptag_same_20", self.WayLookup_ptag_same_20.xdata)
        self.xport.Add("WayLookup_ptag_same_21", self.WayLookup_ptag_same_21.xdata)
        self.xport.Add("WayLookup_ptag_same_22", self.WayLookup_ptag_same_22.xdata)
        self.xport.Add("WayLookup_ptag_same_23", self.WayLookup_ptag_same_23.xdata)
        self.xport.Add("WayLookup_ptag_same_24", self.WayLookup_ptag_same_24.xdata)
        self.xport.Add("WayLookup_ptag_same_25", self.WayLookup_ptag_same_25.xdata)
        self.xport.Add("WayLookup_ptag_same_26", self.WayLookup_ptag_same_26.xdata)
        self.xport.Add("WayLookup_ptag_same_27", self.WayLookup_ptag_same_27.xdata)
        self.xport.Add("WayLookup_ptag_same_28", self.WayLookup_ptag_same_28.xdata)
        self.xport.Add("WayLookup_ptag_same_29", self.WayLookup_ptag_same_29.xdata)
        self.xport.Add("WayLookup_ptag_same_30", self.WayLookup_ptag_same_30.xdata)
        self.xport.Add("WayLookup_ptag_same_31", self.WayLookup_ptag_same_31.xdata)
        self.xport.Add("WayLookup_ptag_same_32", self.WayLookup_ptag_same_32.xdata)
        self.xport.Add("WayLookup_ptag_same_33", self.WayLookup_ptag_same_33.xdata)
        self.xport.Add("WayLookup_ptag_same_34", self.WayLookup_ptag_same_34.xdata)
        self.xport.Add("WayLookup_ptag_same_35", self.WayLookup_ptag_same_35.xdata)
        self.xport.Add("WayLookup_ptag_same_36", self.WayLookup_ptag_same_36.xdata)
        self.xport.Add("WayLookup_ptag_same_37", self.WayLookup_ptag_same_37.xdata)
        self.xport.Add("WayLookup_ptag_same_38", self.WayLookup_ptag_same_38.xdata)
        self.xport.Add("WayLookup_ptag_same_39", self.WayLookup_ptag_same_39.xdata)
        self.xport.Add("WayLookup_ptag_same_40", self.WayLookup_ptag_same_40.xdata)
        self.xport.Add("WayLookup_ptag_same_41", self.WayLookup_ptag_same_41.xdata)
        self.xport.Add("WayLookup_ptag_same_42", self.WayLookup_ptag_same_42.xdata)
        self.xport.Add("WayLookup_ptag_same_43", self.WayLookup_ptag_same_43.xdata)
        self.xport.Add("WayLookup_ptag_same_44", self.WayLookup_ptag_same_44.xdata)
        self.xport.Add("WayLookup_ptag_same_45", self.WayLookup_ptag_same_45.xdata)
        self.xport.Add("WayLookup_ptag_same_46", self.WayLookup_ptag_same_46.xdata)
        self.xport.Add("WayLookup_ptag_same_47", self.WayLookup_ptag_same_47.xdata)
        self.xport.Add("WayLookup_ptag_same_48", self.WayLookup_ptag_same_48.xdata)
        self.xport.Add("WayLookup_ptag_same_49", self.WayLookup_ptag_same_49.xdata)
        self.xport.Add("WayLookup_ptag_same_50", self.WayLookup_ptag_same_50.xdata)
        self.xport.Add("WayLookup_ptag_same_51", self.WayLookup_ptag_same_51.xdata)
        self.xport.Add("WayLookup_ptag_same_52", self.WayLookup_ptag_same_52.xdata)
        self.xport.Add("WayLookup_ptag_same_53", self.WayLookup_ptag_same_53.xdata)
        self.xport.Add("WayLookup_ptag_same_54", self.WayLookup_ptag_same_54.xdata)
        self.xport.Add("WayLookup_ptag_same_55", self.WayLookup_ptag_same_55.xdata)
        self.xport.Add("WayLookup_ptag_same_56", self.WayLookup_ptag_same_56.xdata)
        self.xport.Add("WayLookup_ptag_same_57", self.WayLookup_ptag_same_57.xdata)
        self.xport.Add("WayLookup_ptag_same_58", self.WayLookup_ptag_same_58.xdata)
        self.xport.Add("WayLookup_ptag_same_59", self.WayLookup_ptag_same_59.xdata)
        self.xport.Add("WayLookup_ptag_same_60", self.WayLookup_ptag_same_60.xdata)
        self.xport.Add("WayLookup_ptag_same_61", self.WayLookup_ptag_same_61.xdata)
        self.xport.Add("WayLookup_ptag_same_62", self.WayLookup_ptag_same_62.xdata)
        self.xport.Add("WayLookup_ptag_same_63", self.WayLookup_ptag_same_63.xdata)
        self.xport.Add("WayLookup_entries_0_waymask_0", self.WayLookup_entries_0_waymask_0.xdata)
        self.xport.Add("WayLookup_entries_0_waymask_1", self.WayLookup_entries_0_waymask_1.xdata)
        self.xport.Add("WayLookup_entries_1_waymask_0", self.WayLookup_entries_1_waymask_0.xdata)
        self.xport.Add("WayLookup_entries_1_waymask_1", self.WayLookup_entries_1_waymask_1.xdata)
        self.xport.Add("WayLookup_entries_2_waymask_0", self.WayLookup_entries_2_waymask_0.xdata)
        self.xport.Add("WayLookup_entries_2_waymask_1", self.WayLookup_entries_2_waymask_1.xdata)
        self.xport.Add("WayLookup_entries_3_waymask_0", self.WayLookup_entries_3_waymask_0.xdata)
        self.xport.Add("WayLookup_entries_3_waymask_1", self.WayLookup_entries_3_waymask_1.xdata)
        self.xport.Add("WayLookup_entries_4_waymask_0", self.WayLookup_entries_4_waymask_0.xdata)
        self.xport.Add("WayLookup_entries_4_waymask_1", self.WayLookup_entries_4_waymask_1.xdata)
        self.xport.Add("WayLookup_entries_5_waymask_0", self.WayLookup_entries_5_waymask_0.xdata)
        self.xport.Add("WayLookup_entries_5_waymask_1", self.WayLookup_entries_5_waymask_1.xdata)
        self.xport.Add("WayLookup_entries_6_waymask_0", self.WayLookup_entries_6_waymask_0.xdata)
        self.xport.Add("WayLookup_entries_6_waymask_1", self.WayLookup_entries_6_waymask_1.xdata)
        self.xport.Add("WayLookup_entries_7_waymask_0", self.WayLookup_entries_7_waymask_0.xdata)
        self.xport.Add("WayLookup_entries_7_waymask_1", self.WayLookup_entries_7_waymask_1.xdata)
        self.xport.Add("WayLookup_entries_8_waymask_0", self.WayLookup_entries_8_waymask_0.xdata)
        self.xport.Add("WayLookup_entries_8_waymask_1", self.WayLookup_entries_8_waymask_1.xdata)
        self.xport.Add("WayLookup_entries_9_waymask_0", self.WayLookup_entries_9_waymask_0.xdata)
        self.xport.Add("WayLookup_entries_9_waymask_1", self.WayLookup_entries_9_waymask_1.xdata)
        self.xport.Add("WayLookup_entries_10_waymask_0", self.WayLookup_entries_10_waymask_0.xdata)
        self.xport.Add("WayLookup_entries_10_waymask_1", self.WayLookup_entries_10_waymask_1.xdata)
        self.xport.Add("WayLookup_entries_11_waymask_0", self.WayLookup_entries_11_waymask_0.xdata)
        self.xport.Add("WayLookup_entries_11_waymask_1", self.WayLookup_entries_11_waymask_1.xdata)
        self.xport.Add("WayLookup_entries_12_waymask_0", self.WayLookup_entries_12_waymask_0.xdata)
        self.xport.Add("WayLookup_entries_12_waymask_1", self.WayLookup_entries_12_waymask_1.xdata)
        self.xport.Add("WayLookup_entries_13_waymask_0", self.WayLookup_entries_13_waymask_0.xdata)
        self.xport.Add("WayLookup_entries_13_waymask_1", self.WayLookup_entries_13_waymask_1.xdata)
        self.xport.Add("WayLookup_entries_14_waymask_0", self.WayLookup_entries_14_waymask_0.xdata)
        self.xport.Add("WayLookup_entries_14_waymask_1", self.WayLookup_entries_14_waymask_1.xdata)
        self.xport.Add("WayLookup_entries_15_waymask_0", self.WayLookup_entries_15_waymask_0.xdata)
        self.xport.Add("WayLookup_entries_15_waymask_1", self.WayLookup_entries_15_waymask_1.xdata)
        self.xport.Add("WayLookup_entries_16_waymask_0", self.WayLookup_entries_16_waymask_0.xdata)
        self.xport.Add("WayLookup_entries_16_waymask_1", self.WayLookup_entries_16_waymask_1.xdata)
        self.xport.Add("WayLookup_entries_17_waymask_0", self.WayLookup_entries_17_waymask_0.xdata)
        self.xport.Add("WayLookup_entries_17_waymask_1", self.WayLookup_entries_17_waymask_1.xdata)
        self.xport.Add("WayLookup_entries_18_waymask_0", self.WayLookup_entries_18_waymask_0.xdata)
        self.xport.Add("WayLookup_entries_18_waymask_1", self.WayLookup_entries_18_waymask_1.xdata)
        self.xport.Add("WayLookup_entries_19_waymask_0", self.WayLookup_entries_19_waymask_0.xdata)
        self.xport.Add("WayLookup_entries_19_waymask_1", self.WayLookup_entries_19_waymask_1.xdata)
        self.xport.Add("WayLookup_entries_20_waymask_0", self.WayLookup_entries_20_waymask_0.xdata)
        self.xport.Add("WayLookup_entries_20_waymask_1", self.WayLookup_entries_20_waymask_1.xdata)
        self.xport.Add("WayLookup_entries_21_waymask_0", self.WayLookup_entries_21_waymask_0.xdata)
        self.xport.Add("WayLookup_entries_21_waymask_1", self.WayLookup_entries_21_waymask_1.xdata)
        self.xport.Add("WayLookup_entries_22_waymask_0", self.WayLookup_entries_22_waymask_0.xdata)
        self.xport.Add("WayLookup_entries_22_waymask_1", self.WayLookup_entries_22_waymask_1.xdata)
        self.xport.Add("WayLookup_entries_23_waymask_0", self.WayLookup_entries_23_waymask_0.xdata)
        self.xport.Add("WayLookup_entries_23_waymask_1", self.WayLookup_entries_23_waymask_1.xdata)
        self.xport.Add("WayLookup_entries_24_waymask_0", self.WayLookup_entries_24_waymask_0.xdata)
        self.xport.Add("WayLookup_entries_24_waymask_1", self.WayLookup_entries_24_waymask_1.xdata)
        self.xport.Add("WayLookup_entries_25_waymask_0", self.WayLookup_entries_25_waymask_0.xdata)
        self.xport.Add("WayLookup_entries_25_waymask_1", self.WayLookup_entries_25_waymask_1.xdata)
        self.xport.Add("WayLookup_entries_26_waymask_0", self.WayLookup_entries_26_waymask_0.xdata)
        self.xport.Add("WayLookup_entries_26_waymask_1", self.WayLookup_entries_26_waymask_1.xdata)
        self.xport.Add("WayLookup_entries_27_waymask_0", self.WayLookup_entries_27_waymask_0.xdata)
        self.xport.Add("WayLookup_entries_27_waymask_1", self.WayLookup_entries_27_waymask_1.xdata)
        self.xport.Add("WayLookup_entries_28_waymask_0", self.WayLookup_entries_28_waymask_0.xdata)
        self.xport.Add("WayLookup_entries_28_waymask_1", self.WayLookup_entries_28_waymask_1.xdata)
        self.xport.Add("WayLookup_entries_29_waymask_0", self.WayLookup_entries_29_waymask_0.xdata)
        self.xport.Add("WayLookup_entries_29_waymask_1", self.WayLookup_entries_29_waymask_1.xdata)
        self.xport.Add("WayLookup_entries_30_waymask_0", self.WayLookup_entries_30_waymask_0.xdata)
        self.xport.Add("WayLookup_entries_30_waymask_1", self.WayLookup_entries_30_waymask_1.xdata)
        self.xport.Add("WayLookup_entries_31_waymask_0", self.WayLookup_entries_31_waymask_0.xdata)
        self.xport.Add("WayLookup_entries_31_waymask_1", self.WayLookup_entries_31_waymask_1.xdata)


        # Cascaded ports
        self.WayLookup = self.xport.NewSubPort("WayLookup_")
        self.WayLookup_entries = self.xport.NewSubPort("WayLookup_entries_")
        self.WayLookup_entries_0 = self.xport.NewSubPort("WayLookup_entries_0_")
        self.WayLookup_entries_0_itlb = self.xport.NewSubPort("WayLookup_entries_0_itlb_")
        self.WayLookup_entries_0_itlb_exception = self.xport.NewSubPort("WayLookup_entries_0_itlb_exception_")
        self.WayLookup_entries_0_itlb_pbmt = self.xport.NewSubPort("WayLookup_entries_0_itlb_pbmt_")
        self.WayLookup_entries_0_meta_codes = self.xport.NewSubPort("WayLookup_entries_0_meta_codes_")
        self.WayLookup_entries_0_ptag = self.xport.NewSubPort("WayLookup_entries_0_ptag_")
        self.WayLookup_entries_0_vSetIdx = self.xport.NewSubPort("WayLookup_entries_0_vSetIdx_")
        self.WayLookup_entries_0_waymask = self.xport.NewSubPort("WayLookup_entries_0_waymask_")
        self.WayLookup_entries_1 = self.xport.NewSubPort("WayLookup_entries_1_")
        self.WayLookup_entries_1_waymask = self.xport.NewSubPort("WayLookup_entries_1_waymask_")
        self.WayLookup_entries_10 = self.xport.NewSubPort("WayLookup_entries_10_")
        self.WayLookup_entries_10_waymask = self.xport.NewSubPort("WayLookup_entries_10_waymask_")
        self.WayLookup_entries_11 = self.xport.NewSubPort("WayLookup_entries_11_")
        self.WayLookup_entries_11_waymask = self.xport.NewSubPort("WayLookup_entries_11_waymask_")
        self.WayLookup_entries_12 = self.xport.NewSubPort("WayLookup_entries_12_")
        self.WayLookup_entries_12_waymask = self.xport.NewSubPort("WayLookup_entries_12_waymask_")
        self.WayLookup_entries_13 = self.xport.NewSubPort("WayLookup_entries_13_")
        self.WayLookup_entries_13_waymask = self.xport.NewSubPort("WayLookup_entries_13_waymask_")
        self.WayLookup_entries_14 = self.xport.NewSubPort("WayLookup_entries_14_")
        self.WayLookup_entries_14_waymask = self.xport.NewSubPort("WayLookup_entries_14_waymask_")
        self.WayLookup_entries_15 = self.xport.NewSubPort("WayLookup_entries_15_")
        self.WayLookup_entries_15_waymask = self.xport.NewSubPort("WayLookup_entries_15_waymask_")
        self.WayLookup_entries_16 = self.xport.NewSubPort("WayLookup_entries_16_")
        self.WayLookup_entries_16_waymask = self.xport.NewSubPort("WayLookup_entries_16_waymask_")
        self.WayLookup_entries_17 = self.xport.NewSubPort("WayLookup_entries_17_")
        self.WayLookup_entries_17_waymask = self.xport.NewSubPort("WayLookup_entries_17_waymask_")
        self.WayLookup_entries_18 = self.xport.NewSubPort("WayLookup_entries_18_")
        self.WayLookup_entries_18_waymask = self.xport.NewSubPort("WayLookup_entries_18_waymask_")
        self.WayLookup_entries_19 = self.xport.NewSubPort("WayLookup_entries_19_")
        self.WayLookup_entries_19_waymask = self.xport.NewSubPort("WayLookup_entries_19_waymask_")
        self.WayLookup_entries_2 = self.xport.NewSubPort("WayLookup_entries_2_")
        self.WayLookup_entries_2_waymask = self.xport.NewSubPort("WayLookup_entries_2_waymask_")
        self.WayLookup_entries_20 = self.xport.NewSubPort("WayLookup_entries_20_")
        self.WayLookup_entries_20_waymask = self.xport.NewSubPort("WayLookup_entries_20_waymask_")
        self.WayLookup_entries_21 = self.xport.NewSubPort("WayLookup_entries_21_")
        self.WayLookup_entries_21_waymask = self.xport.NewSubPort("WayLookup_entries_21_waymask_")
        self.WayLookup_entries_22 = self.xport.NewSubPort("WayLookup_entries_22_")
        self.WayLookup_entries_22_waymask = self.xport.NewSubPort("WayLookup_entries_22_waymask_")
        self.WayLookup_entries_23 = self.xport.NewSubPort("WayLookup_entries_23_")
        self.WayLookup_entries_23_waymask = self.xport.NewSubPort("WayLookup_entries_23_waymask_")
        self.WayLookup_entries_24 = self.xport.NewSubPort("WayLookup_entries_24_")
        self.WayLookup_entries_24_waymask = self.xport.NewSubPort("WayLookup_entries_24_waymask_")
        self.WayLookup_entries_25 = self.xport.NewSubPort("WayLookup_entries_25_")
        self.WayLookup_entries_25_waymask = self.xport.NewSubPort("WayLookup_entries_25_waymask_")
        self.WayLookup_entries_26 = self.xport.NewSubPort("WayLookup_entries_26_")
        self.WayLookup_entries_26_waymask = self.xport.NewSubPort("WayLookup_entries_26_waymask_")
        self.WayLookup_entries_27 = self.xport.NewSubPort("WayLookup_entries_27_")
        self.WayLookup_entries_27_waymask = self.xport.NewSubPort("WayLookup_entries_27_waymask_")
        self.WayLookup_entries_28 = self.xport.NewSubPort("WayLookup_entries_28_")
        self.WayLookup_entries_28_waymask = self.xport.NewSubPort("WayLookup_entries_28_waymask_")
        self.WayLookup_entries_29 = self.xport.NewSubPort("WayLookup_entries_29_")
        self.WayLookup_entries_29_waymask = self.xport.NewSubPort("WayLookup_entries_29_waymask_")
        self.WayLookup_entries_3 = self.xport.NewSubPort("WayLookup_entries_3_")
        self.WayLookup_entries_3_waymask = self.xport.NewSubPort("WayLookup_entries_3_waymask_")
        self.WayLookup_entries_30 = self.xport.NewSubPort("WayLookup_entries_30_")
        self.WayLookup_entries_30_waymask = self.xport.NewSubPort("WayLookup_entries_30_waymask_")
        self.WayLookup_entries_31 = self.xport.NewSubPort("WayLookup_entries_31_")
        self.WayLookup_entries_31_waymask = self.xport.NewSubPort("WayLookup_entries_31_waymask_")
        self.WayLookup_entries_4 = self.xport.NewSubPort("WayLookup_entries_4_")
        self.WayLookup_entries_4_waymask = self.xport.NewSubPort("WayLookup_entries_4_waymask_")
        self.WayLookup_entries_5 = self.xport.NewSubPort("WayLookup_entries_5_")
        self.WayLookup_entries_5_waymask = self.xport.NewSubPort("WayLookup_entries_5_waymask_")
        self.WayLookup_entries_6 = self.xport.NewSubPort("WayLookup_entries_6_")
        self.WayLookup_entries_6_waymask = self.xport.NewSubPort("WayLookup_entries_6_waymask_")
        self.WayLookup_entries_7 = self.xport.NewSubPort("WayLookup_entries_7_")
        self.WayLookup_entries_7_waymask = self.xport.NewSubPort("WayLookup_entries_7_waymask_")
        self.WayLookup_entries_8 = self.xport.NewSubPort("WayLookup_entries_8_")
        self.WayLookup_entries_8_waymask = self.xport.NewSubPort("WayLookup_entries_8_waymask_")
        self.WayLookup_entries_9 = self.xport.NewSubPort("WayLookup_entries_9_")
        self.WayLookup_entries_9_waymask = self.xport.NewSubPort("WayLookup_entries_9_waymask_")
        self.WayLookup_gpf = self.xport.NewSubPort("WayLookup_gpf_")
        self.WayLookup_gpf_entry = self.xport.NewSubPort("WayLookup_gpf_entry_")
        self.WayLookup_readPtr = self.xport.NewSubPort("WayLookup_readPtr_")
        self.WayLookup_writePtr = self.xport.NewSubPort("WayLookup_writePtr_")
        self.io = self.xport.NewSubPort("io_")
        self.io_read = self.xport.NewSubPort("io_read_")
        self.io_read_bits = self.xport.NewSubPort("io_read_bits_")
        self.io_read_bits_entry = self.xport.NewSubPort("io_read_bits_entry_")
        self.io_read_bits_entry_itlb = self.xport.NewSubPort("io_read_bits_entry_itlb_")
        self.io_read_bits_entry_itlb_exception = self.xport.NewSubPort("io_read_bits_entry_itlb_exception_")
        self.io_read_bits_entry_itlb_pbmt = self.xport.NewSubPort("io_read_bits_entry_itlb_pbmt_")
        self.io_read_bits_entry_meta_codes = self.xport.NewSubPort("io_read_bits_entry_meta_codes_")
        self.io_read_bits_entry_ptag = self.xport.NewSubPort("io_read_bits_entry_ptag_")
        self.io_read_bits_entry_vSetIdx = self.xport.NewSubPort("io_read_bits_entry_vSetIdx_")
        self.io_read_bits_entry_waymask = self.xport.NewSubPort("io_read_bits_entry_waymask_")
        self.io_read_bits_gpf = self.xport.NewSubPort("io_read_bits_gpf_")
        self.io_update = self.xport.NewSubPort("io_update_")
        self.io_update_bits = self.xport.NewSubPort("io_update_bits_")
        self.io_write = self.xport.NewSubPort("io_write_")
        self.io_write_bits = self.xport.NewSubPort("io_write_bits_")
        self.io_write_bits_entry = self.xport.NewSubPort("io_write_bits_entry_")
        self.io_write_bits_entry_itlb = self.xport.NewSubPort("io_write_bits_entry_itlb_")
        self.io_write_bits_entry_itlb_exception = self.xport.NewSubPort("io_write_bits_entry_itlb_exception_")
        self.io_write_bits_entry_itlb_pbmt = self.xport.NewSubPort("io_write_bits_entry_itlb_pbmt_")
        self.io_write_bits_entry_meta_codes = self.xport.NewSubPort("io_write_bits_entry_meta_codes_")
        self.io_write_bits_entry_ptag = self.xport.NewSubPort("io_write_bits_entry_ptag_")
        self.io_write_bits_entry_vSetIdx = self.xport.NewSubPort("io_write_bits_entry_vSetIdx_")
        self.io_write_bits_entry_waymask = self.xport.NewSubPort("io_write_bits_entry_waymask_")
        self.io_write_bits_gpf = self.xport.NewSubPort("io_write_bits_gpf_")


    def __del__(self):
        self.Finish()

    ################################
    #         User APIs            #
    ################################
    def InitClock(self, name: str):
        self.xclock.Add(self.xport[name])

    def Step(self, i:int = 1):
        self.xclock.Step(i)

    def StepRis(self, callback, args=(), kwargs={}):
        self.xclock.StepRis(callback, args, kwargs)

    def StepFal(self, callback, args=(), kwargs={}):
        self.xclock.StepFal(callback, args, kwargs)

    def ResumeWaveformDump(self):
        return self.dut.ResumeWaveformDump()

    def PauseWaveformDump(self):
        return self.dut.PauseWaveformDump()

    def WaveformPaused(self) -> int:
        """ Returns 1 if waveform export is paused """
        return self.dut.WaveformPaused()

    def GetXPort(self):
        return self.xport

    def GetXClock(self):
        return self.xclock

    def SetWaveform(self, filename: str):
        self.dut.SetWaveform(filename)

    def GetWaveFormat(self) -> str:
        """
        Get the waveform extension, or an empty string if disabled.

        Returns:
            str: The extension of waveform file.
        """
        return self.dut.GetWaveFormat()

    def FlushWaveform(self):
        self.dut.FlushWaveform()

    def SetCoverage(self, filename: str):
        self.dut.SetCoverage(filename)

    def GetCovMetrics(self) -> int:
        """
        Get the bitmask for collected coverage metrics. 0 means coverage is disabled

        Returns:
            int: Collected coverage metrics bitmask:
                - Bit 0: line   (Line coverage)
                - Bit 1: cond   (Condition coverage)
                - Bit 2: fsm    (Finite-State Machine coverage)
                - Bit 3: toggle (Toggle coverage)
                - Bit 4: branch (Branch coverage)
                - Bit 5: assert (Assertion coverage)
        """
        return self.dut.GetCovMetrics()
    
    def CheckPoint(self, name: str) -> int:
        self.dut.CheckPoint(name)

    def Restore(self, name: str) -> int:
        self.dut.Restore(name)

    def GetInternalSignal(self, name: str, index=-1, is_array=False, use_vpi=False):
        if name not in self.internal_signals:
            signal = None
            if self.dut.GetXSignalCFGBasePtr() != 0 and not use_vpi:
                xname = "CFG:" + name
                if is_array:
                    assert index < 0, "Index is not supported for array signal"
                    signal = self.xcfg.NewXDataArray(name, xname)
                elif index >= 0:
                    signal = self.xcfg.NewXData(name, index, xname)
                else:
                    signal = self.xcfg.NewXData(name, xname)
            else:
                assert index < 0, "Index is not supported for VPI signal"
                assert not is_array, "Array is not supported for VPI signal"
                signal = xsp.XData.FromVPI(self.dut.GetVPIHandleObj(name),
                                           self.dut.GetVPIFuncPtr("vpi_get"),
                                           self.dut.GetVPIFuncPtr("vpi_get_value"),
                                           self.dut.GetVPIFuncPtr("vpi_put_value"), "VPI:" + name)
                if use_vpi:
                    assert signal is not None, f"Internal signal {name} not found (Check VPI is enabled)"
            if signal is None:
                return None
            if not isinstance(signal, xsp.XData):
                self.internal_signals[name] = [xsp.XPin(s, self.event) for s in signal]
            else:
                self.internal_signals[name] = xsp.XPin(signal, self.event)
        return self.internal_signals[name]

    def GetInternalSignalList(self, prefix="", deep=99, use_vpi=False):
        if self.dut.GetXSignalCFGBasePtr() != 0 and not use_vpi:
            return self.xcfg.GetSignalNames(prefix)
        else:
            return self.dut.VPIInternalSignalList(prefix, deep)

    def VPIInternalSignalList(self, prefix="", deep=99):
        return self.dut.VPIInternalSignalList(prefix, deep)

    def Finish(self):
        self.dut.Finish()

    def RefreshComb(self):
        self.dut.RefreshComb()

    ################################
    #      End of User APIs        #
    ################################

    def __getitem__(self, key):
        return xsp.XPin(self.port[key], self.event)

    # Async APIs wrapped from XClock
    async def AStep(self,i: int):
        return await self.xclock.AStep(i)

    async def ACondition(self,fc_cheker):
        return await self.xclock.ACondition(fc_cheker)

    def RunStep(self,i: int):
        return self.xclock.RunStep(i)

    def __setattr__(self, name, value):
        assert not isinstance(getattr(self, name, None),
                              (xsp.XPin, xsp.XData)), \
        f"XPin and XData of DUT are read-only, do you mean to set the value of the signal? please use `{name}.value = ` instead."
        return super().__setattr__(name, value)


if __name__=="__main__":
    dut=DUTWayLookup()
    dut.Step(100)
